In [1]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/023/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_cienciapolitica.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/023/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 372 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_cienciapolitica.csv
   372 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          313
ALCANZÓ VACANTE           56
INHABILITADO (Art. 5)      2
AUSENTE                    1

── Estadísticas de puntaje ──
count     371.000
mean      896.310
std       167.461
min       434.875
25%       778.438
50%       902.500
75%      1011.625
max      1330.125

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,739314,"Aburto Chavez, Verenisce Bilha",CIENCIA POLÍTICA,774.625,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
1,696050,"Acharte Laura, Angela Luz",CIENCIA POLÍTICA,713.500,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
2,723870,"Aguilar Salazar, Walter Fabián",CIENCIA POLÍTICA,627.625,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
3,826969,"Aguilera Cortez, Aslhy Brigitte",CIENCIA POLÍTICA,838.000,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
4,762581,"Aguirre Valdez, Ariana Paola",CIENCIA POLÍTICA,1007.500,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
5,813783,"Agurto Garcia, Hallibeth Jeissy",CIENCIA POLÍTICA,731.625,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
6,825822,"Alarcon Muñoz, Sebastián José",CIENCIA POLÍTICA,669.625,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
7,791271,"Alcalá Vargas, Nicole Aurora",CIENCIA POLÍTICA,434.875,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
8,685412,"Alegre Lopez, Enzo Ruben",CIENCIA POLÍTICA,839.250,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
9,711946,"Allain Ramos, Milagros Esther",CIENCIA POLÍTICA,810.125,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
10,775653,"Allca Quispe, Joyce Maria",CIENCIA POLÍTICA,995.500,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
11,704808,"Alva Ramirez, Ana Isaura",CIENCIA POLÍTICA,970.000,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
12,747942,"Alvarez Chuco, Aviles Felix",CIENCIA POLÍTICA,902.125,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
13,813023,"Alvarez Ubillus, Odessa Antonette",CIENCIA POLÍTICA,728.375,NaN,SIN OBSERVACIÓN,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...
14,838977,"Anco Velasquez, Nayeli Tatiana",CIENCIA POLÍTICA,1092.750,45.0,ALCANZÓ VACANTE,CIENCIA POLÍTICA,https://admision.unmsm.edu.pe/Website20262/A/0...

In [2]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_cienciapolitica.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: CIENCIA POLÍTICA
Vacantes obtenidas: 56
Puntaje máximo: 1330.125
Puntaje mínimo: 1070.375

    codigo                      apellidos_nombres   puntaje  merito_ep
0   693125             Prieto Alvarado, Mell Rose  1330.125        1.0
1   809215           Jamanca Ojeda, Laura Rosenda  1320.000        2.0
2   690588        Caira Bautista, Roxana Giomaira  1314.125        3.0
3   750185       Andueza Espinoza, Williams Farel  1285.000        4.0
4   742515          Bendezu Chipana, Andre Leonel  1283.875        5.0
5   751270    Fernandez Reyes, Gabriela Elizabeth  1274.875        6.0
6   832339                Torres Vilcabana, Diego  1265.750        7.0
7   727663      Ñaupari Maldonado, Benjamin Isaac  1224.625        8.0
8   778810     Cortez Maldonado, Daniela Fernanda  1223.500        9.0
9   771479       Chamorro Enriquez, Angel Wilians  1206.375       10.0
10  720150       Espinoza Pizarro, Diana Milagros  1198.375       11.0
11  794635       Romualdo Tordecillo, Juan Andreé  1193.625       12.0
12  800893      Monigote Castillo, Sharon Giselle  1190.875       13.0
13  774195       Guillen Mejia, Josselyn Jessenia  1189.250       15.0
14  691787       Pumayalli Pomacosi, Percy Junior  1189.250       14.0
15  752482            Maldonado Rado, Maria Julia  1184.500       16.0
16  836367      Bazan Mendez, Guadalupe Madeleine  1177.750       17.0
17  837070             Leon Bobadilla, Jhon Frank  1173.250       18.0
18  733906         Rentera Arredondo, Ruben Dario  1162.625       19.0
19  769277      Lopez Shupingahua, Brander Heller  1158.375       20.0
20  722897           Ubillus Rojas, Fabian Arturo  1157.250       21.0
21  828215    Prado Ramon, Noemí Miranda Milagros  1150.375       22.0
22  724882           Caycho Gonzales, Alexa Paola  1146.375       23.0
23  779848         Gonzales Orozco, Juana Luciana  1142.375       24.0
24  792213          Valencia Loaiza, Jazmín Alelí  1136.000       25.0
25  685440      Gutierrez Coras, Adelson Aldahier  1135.000       26.0
26  742293           Santos Zegarra, Jose Ernesto  1131.000       27.0
27  795447               Pinto Frias, Cesar Elvis  1129.875       30.0
28  706998     Quispe Parhuayo, Cristofer Enrique  1129.875       29.0
29  753623          Llampi Quispe, Angielly Thair  1129.875       28.0
30  771897       Galindo Reátegui, Enzo Valentino  1125.875       31.0
31  825494           Yaranga Lopez, Edhuin Didier  1123.000       33.0
32  817233       Arias Escalante, Aldair Leonardo  1123.000       32.0
33  703270             Guzman Angulo, Kerin Cesia  1122.750       34.0
34  694382         Hervias Rivas, Angeles Yomaira  1113.875       35.0
35  825448            Rupay Huacan, Andrea Nicole  1112.125       36.0
36  816078       Rivera Berrios, Carolina Juiomar  1109.875       37.0
37  692001         Maldonado Ruiz, Kevín Fabricio  1108.750       38.0
38  800486           Corra Huapalla, Eliana Belen  1107.000       39.0
39  752273               Gamarra Maza, Ariana Mia  1105.875       40.0
40  734365        Shapiama Lozano, Maria Fernanda  1105.750       41.0
41  826618              Bedoya Arias, Keith Kiara  1104.125       42.0
42  724560         Arone Gutierrez, Samira Jazmin  1099.500       43.0
43  787387       Tohalino Vidal, Fernando Anthony  1096.750       44.0
44  838977         Anco Velasquez, Nayeli Tatiana  1092.750       45.0
45  705503           Poma Vilcapoma, Matias Pedro  1092.750       46.0
46  728271            Cama Vilca, Hailton Gerardo  1091.625       47.0
47  685447               Ramos Mego, Brayan Nixon  1086.625       48.0
48  783169         Quispe Mamani, Natali Estefany  1085.250       49.0
49  738385      Ticona Farfán, Alison Del Rosario  1085.125       50.0
50  692371         Coral Arevalo, Sebastian Alain  1083.625       52.0
51  811808              Laya Torres, José Alberto  1083.625       51.0
52  843886        Ventura Yupanqui, Marco Antonio  1081.500       53.0
53  694055         Motta Cribilleros, Pablo Mateo  1081.250       54.0
54  779033          Quinto Cubas, Kristell Mayela  1073.250       55.0
55  784765  Valladolid Fernandez, Antuanela Mayra  1070.375       56.0

In [3]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/101/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_biologia.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/101/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 187 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_biologia.csv
   187 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          140
ALCANZÓ VACANTE           45
AUSENTE                    1
INHABILITADO (Art. 5)      1

── Estadísticas de puntaje ──
count     186.000
mean      853.335
std       161.680
min       403.125
25%       742.250
50%       839.250
75%       958.562
max      1277.750

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,218537,"Acquaviva Romero, Francesca Lucciana",CIENCIAS BIOLÓGICAS,1021.250,31.0,ALCANZÓ VACANTE,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
1,215726,"Alania Espejo, Emili Angheli",CIENCIAS BIOLÓGICAS,919.750,NaN,SIN OBSERVACIÓN,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
2,210532,"Alaya Talavera, Zumiko Satomy Anthonella",CIENCIAS BIOLÓGICAS,758.625,NaN,SIN OBSERVACIÓN,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
3,211905,"Alegre Martinez, Matias Sebastian",CIENCIAS BIOLÓGICAS,843.500,NaN,SIN OBSERVACIÓN,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
4,219950,"Alegria Garcia, Jhosep Smith",CIENCIAS BIOLÓGICAS,692.750,NaN,SIN OBSERVACIÓN,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
5,210578,"Altamirano Laveriano, Alexis Aimar",CIENCIAS BIOLÓGICAS,1016.250,33.0,ALCANZÓ VACANTE,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
6,216868,"Altamirano Salvador, Arely Andrea",CIENCIAS BIOLÓGICAS,614.875,NaN,SIN OBSERVACIÓN,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
7,218433,"Amaut Bendezu, Jestyn Braison",CIENCIAS BIOLÓGICAS,759.875,NaN,SIN OBSERVACIÓN,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
8,211016,"Ambicho Oscco, Alejandro David",CIENCIAS BIOLÓGICAS,941.375,NaN,SIN OBSERVACIÓN,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
9,218136,"Ambrosio Silva, Roberto David",CIENCIAS BIOLÓGICAS,754.125,NaN,SIN OBSERVACIÓN,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
10,211482,"Andia Arce, Rosalin",CIENCIAS BIOLÓGICAS,1132.125,9.0,ALCANZÓ VACANTE,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
11,212193,"Aponte Hoyle, Yasmile Abigail",CIENCIAS BIOLÓGICAS,1096.750,13.0,ALCANZÓ VACANTE,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
12,217382,"Arca Campos, Marina Luana",CIENCIAS BIOLÓGICAS,739.750,NaN,SIN OBSERVACIÓN,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
13,213934,"Arenas Huaringa, Ariana Azumi",CIENCIAS BIOLÓGICAS,811.750,NaN,SIN OBSERVACIÓN,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...
14,218909,"Arias Lazaro, Jefry Joel",CIENCIAS BIOLÓGICAS,762.750,NaN,SIN OBSERVACIÓN,CIENCIAS BIOLÓGICAS,https://admision.unmsm.edu.pe/Website20262/A/1...

In [4]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_biologia.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: CIENCIAS BIOLÓGICAS
Vacantes obtenidas: 45
Puntaje máximo: 1277.75
Puntaje mínimo: 964.125

    codigo                      apellidos_nombres   puntaje  merito_ep
0   212822              Cieza Chávez, Adrián Asad  1277.750        1.0
1   216177         Souza Sabogal, Benjamín Daniel  1265.750        2.0
2   216052      Caruajulca Eugenio, Noemi Abigail  1253.500        3.0
3   213686               Oliva Leon, Abhryl Luana  1248.000        4.0
4   211173            Torpoco Capcha, José Manuel  1210.375        5.0
5   214120              Soto Zumaran, Alexa Thais  1193.250        6.0
6   213250            Zegarra Mamani, Enzo Alonso  1155.500        7.0
7   215954     Quiroz Valenzuela, Maria Alejandra  1150.875        8.0
8   211482                    Andia Arce, Rosalin  1132.125        9.0
9   210974    Cruz Condori, Marco Antonio Ernesto  1131.000       10.0
10  216581            Montenegro Maza, Kevin Joel  1128.625       11.0
11  211691           Melendez Gonzales, Ever Abel  1111.000       12.0
12  212193          Aponte Hoyle, Yasmile Abigail  1096.750       13.0
13  210891                 Paz Neyra, Pablo Uriel  1084.750       14.0
14  216418         Ludeña Bocanegra, Braulio Joel  1084.750       15.0
15  217740       Peralta Alcantara, Adrian Alonso  1083.625       16.0
16  214809         Vasquez Gallardo, Diego Alonso  1079.625       17.0
17  216653           Rodriguez Moreno, Leia Marie  1062.750       18.0
18  214023           Cotrina Cruz, Romy Alexandra  1062.500       19.0
19  213873         Roncal Valdivia, Grace Dajanna  1058.500       20.0
20  218406        Callupe Kimura, Nicolas Kiyoshi  1055.625       21.0
21  212682            Muñoz Loayza, Ariana Melani  1053.250       22.0
22  218374        Santillan Doria, Greysi Katerin  1045.375       23.0
23  216386         Portugal Cabana, Keila Xiomara  1041.375       24.0
24  213226     Solórzano Millán, Luciana Victoria  1037.375       26.0
25  217107  Quispe Huamán, Rodrigo Alonso Gabriel  1037.375       25.0
26  211412           Ganoza Deur, Nayely Carolina  1034.500       27.0
27  218903              Cuya Janampa, Sol Xiomara  1031.625       28.0
28  213035          Olivos Izquierdo, Piero Aaron  1025.625       29.0
29  213688   Saavedra Delgado, Christopher Efrain  1021.875       30.0
30  218537   Acquaviva Romero, Francesca Lucciana  1021.250       31.0
31  213738         Huaman Castañeda, Kamila Celia  1020.750       32.0
32  210578     Altamirano Laveriano, Alexis Aimar  1016.250       33.0
33  218648    Caballero Cervera, Estrella Miranda  1013.625       34.0
34  212790       Salinas Rafael, Nayely Estefania  1002.500       35.0
35  214334         Quispe Rojas, Mariel Valentina   997.250       36.0
36  217274             Garcia Albino, Cielo Annie   995.125       37.0
37  216149                     Medina Piedra, Mia   978.000       38.0
38  219435   Custodio Castillo, Sebastian Antonio   976.250       39.0
39  219745              Cruz Alfaro, Reinad Pablo   972.625       40.0
40  214511                Nuñez Saavedra, Solange   972.250       41.0
41  214316            Tapia Torres, Leslie Johana   970.000       42.0
42  215632             Zumaeta Mas, Leandro Marat   967.500       43.0
43  210765           Berna Alvarez, Kevin Rosendo   964.875       44.0
44  211737      Bustamante Cavero, Irene Berthila   964.125       45.0

In [5]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/145/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_computacioncientifica.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/145/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 42 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_computacioncientifica.csv
   42 filas  ×  8 columnas

── Observaciones ──
observacion
ALCANZÓ VACANTE    42

── Estadísticas de puntaje ──
count      42.000
mean      770.717
std       137.794
min       576.000
25%       657.781
50%       760.375
75%       858.375
max      1054.500

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,219773,"Alarcon Atauje, Ezzio Cesar Manases",COMPUTACIÓN CIENTÍFICA,860.375,11,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
1,217075,"Amaya Aquino, Solanghs Julient Milagros",COMPUTACIÓN CIENTÍFICA,908.125,7,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
2,217935,"Ambrocio Estela, Edinson Francisco",COMPUTACIÓN CIENTÍFICA,1020.250,2,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
3,218732,"Atto Salhua, Yinnsu Satomy",COMPUTACIÓN CIENTÍFICA,578.125,42,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
4,217838,"Barbadillo Silva, Cristoper Junior",COMPUTACIÓN CIENTÍFICA,826.125,15,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
5,213692,"Beltran Castillo, Miguel Angel",COMPUTACIÓN CIENTÍFICA,609.875,37,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
6,215948,"Benites Olivos, Leonardo Fabricio",COMPUTACIÓN CIENTÍFICA,678.250,30,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
7,214405,"Bravo Espinoza, Max Eduar",COMPUTACIÓN CIENTÍFICA,809.000,17,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
8,210755,"Caceres Sarmiento, Milagros Sunmy",COMPUTACIÓN CIENTÍFICA,758.750,22,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
9,219598,"Cajas Aquino, Luis Alvaro",COMPUTACIÓN CIENTÍFICA,1020.250,3,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
10,212091,"Chalco Inga, Josue Alexander Willy",COMPUTACIÓN CIENTÍFICA,823.250,16,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
11,215060,"Chavez Justiniano, Yhadira Matilde",COMPUTACIÓN CIENTÍFICA,590.875,40,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
12,212049,"Collantes Sanchez, Adriano Guissepi",COMPUTACIÓN CIENTÍFICA,642.625,35,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
13,216335,"De La Cruz Silva, Steven",COMPUTACIÓN CIENTÍFICA,1054.500,1,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...
14,217145,"Guevara Enrique, Paolo Alexander",COMPUTACIÓN CIENTÍFICA,682.250,29,ALCANZÓ VACANTE,COMPUTACIÓN CIENTÍFICA,https://admision.unmsm.edu.pe/Website20262/A/1...

In [6]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_computacioncientifica.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: COMPUTACIÓN CIENTÍFICA
Vacantes obtenidas: 42
Puntaje máximo: 1054.5
Puntaje mínimo: 576.0

    codigo                         apellidos_nombres   puntaje  merito_ep
0   216335                  De La Cruz Silva, Steven  1054.500          1
1   219598                 Cajas Aquino, Luis Alvaro  1020.250          3
2   217935        Ambrocio Estela, Edinson Francisco  1020.250          2
3   218419              Maldonado Oré, Javier Shande  1009.375          4
4   213306                Heredia Carranza, Joycelyn   979.625          5
5   218332        Villon Barrientos, Fabiana Valeria   952.875          6
6   217075   Amaya Aquino, Solanghs Julient Milagros   908.125          7
7   216818              Santos Salazar, Angel Berlin   903.750          8
8   216521           Moreno Cardenas, Felipe Hilario   900.375          9
9   217917           Paccochuco Herrera, Nelson Abel   895.750         10
10  219773       Alarcon Atauje, Ezzio Cesar Manases   860.375         11
11  218680                 Reategui Ventura, Eduardo   852.375         12
12  216950       Martinez Palomino, Bruno Sebasthian   847.250         13
13  216814             Gutierrez Gutierrez, Gabriela   834.125         14
14  217838        Barbadillo Silva, Cristoper Junior   826.125         15
15  212091        Chalco Inga, Josue Alexander Willy   823.250         16
16  214405                 Bravo Espinoza, Max Eduar   809.000         17
17  211872          Malapi Segura, Angelina Domenica   779.125         18
18  214841               Vasquez Arce, Piero Antonio   768.375         19
19  214953  Villavicencio Tamara, Santiago Alejandro   762.750         20
20  219303              Huarcaya Saldaña, Joe Javier   762.000         21
21  210755         Caceres Sarmiento, Milagros Sunmy   758.750         22
22  219038                Quina Nuñez, Denisse Sofia   750.500         23
23  216995           Salvatierra Ore, Esteban Andrés   726.375         24
24  213831               Quispe Apaza, Marycris Lady   725.125         25
25  210285               Villa Romero, Maycol Adrian   709.250         26
26  218523       Montes Gutierrez, Eduardo Sebastian   693.500         27
27  215916           Romero Mogollón, Ernesto Manuel   692.250         28
28  217145          Guevara Enrique, Paolo Alexander   682.250         29
29  215948         Benites Olivos, Leonardo Fabricio   678.250         30
30  214343          Medina Suarez, Jennifer Milagros   668.375         32
31  215642          Merino Carhuapoma, Doriam Colynh   654.250         33
32  215590             Robles Espinoza, Sergio Paulo   646.125         34
33  212049       Collantes Sanchez, Adriano Guissepi   642.625         35
34  216167                  Mamani Gutiérrez, Antony   642.125         36
35  213692            Beltran Castillo, Miguel Angel   609.875         37
36  214168          Ruiz Calatayud, Ricardo Al Farid   594.875         39
37  216197               Paucar Joaquin, Johan Andre   594.875         38
38  215060        Chavez Justiniano, Yhadira Matilde   590.875         40
39  213254                    Noel Vargas, Alexander   586.125         41
40  218732                Atto Salhua, Yinnsu Satomy   578.125         42
41  218582              Lavado Choque, Andrew Xavier   576.000         43

In [7]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/035/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_comu.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/035/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 301 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_comu.csv
   301 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          266
ALCANZÓ VACANTE           32
AUSENTE                    2
INHABILITADO (Art. 5)      1

── Estadísticas de puntaje ──
count     299.000
mean      848.842
std       189.064
min       290.750
25%       721.688
50%       851.875
75%       986.625
max      1325.125

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,797795,"Acosta Huamani, Azalea Sady",COMUNICACIÓN SOCIAL,1245.750,5.0,ALCANZÓ VACANTE,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
1,741684,"Acuña Ramirez, Gabriela",COMUNICACIÓN SOCIAL,758.125,NaN,SIN OBSERVACIÓN,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
2,689172,"Aguilar Ramirez, Victoria Gabriela",COMUNICACIÓN SOCIAL,573.250,NaN,SIN OBSERVACIÓN,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
3,707044,"Aguirre Lozano, Alisson Jimena",COMUNICACIÓN SOCIAL,985.375,NaN,SIN OBSERVACIÓN,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
4,792461,"Alberto Valiente, Katia Marlene",COMUNICACIÓN SOCIAL,864.375,NaN,SIN OBSERVACIÓN,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
5,789751,"Alcala Sanchez, Sofia Alejanddra",COMUNICACIÓN SOCIAL,692.125,NaN,SIN OBSERVACIÓN,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
6,691250,"Alcalá Torres, Tatiana Valeria",COMUNICACIÓN SOCIAL,1148.125,23.0,ALCANZÓ VACANTE,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
7,690148,"Alcantara Galindo, Anderson Deyvis",COMUNICACIÓN SOCIAL,720.500,NaN,SIN OBSERVACIÓN,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
8,798835,"Aliaga Vargas, Evan Owen",COMUNICACIÓN SOCIAL,670.500,NaN,SIN OBSERVACIÓN,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
9,738148,"Allcarima Libia, Nayely Kiara",COMUNICACIÓN SOCIAL,869.500,NaN,SIN OBSERVACIÓN,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
10,687713,"Alva Rodriguez, Giancarlo Alexis",COMUNICACIÓN SOCIAL,1021.375,NaN,SIN OBSERVACIÓN,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
11,685683,"Alvarado Acuña, Diego Sebastian",COMUNICACIÓN SOCIAL,958.000,NaN,SIN OBSERVACIÓN,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
12,755081,"Alvarado Zapata, Renzo Rafael",COMUNICACIÓN SOCIAL,815.250,NaN,SIN OBSERVACIÓN,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
13,733504,"Alvarez Aco, Gianmarco Anthony",COMUNICACIÓN SOCIAL,885.500,NaN,SIN OBSERVACIÓN,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
14,768502,"Alvarez Benites, Lorena Patricia",COMUNICACIÓN SOCIAL,1119.000,26.0,ALCANZÓ VACANTE,COMUNICACIÓN SOCIAL,https://admision.unmsm.edu.pe/Website20262/A/0...

In [8]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_comu.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: COMUNICACIÓN SOCIAL
Vacantes obtenidas: 32
Puntaje máximo: 1325.125
Puntaje mínimo: 1099.0

    codigo                         apellidos_nombres   puntaje  merito_ep
0   819022             Collahua Torres, Josue Moises  1325.125        1.0
1   694160            Cuyubamba Coronel, David Elias  1294.875        2.0
2   702226          Villanueva Flores, Angelo Junior  1294.875        3.0
3   750373            Quiroz Ronceros, David Antonio  1264.000        4.0
4   797795               Acosta Huamani, Azalea Sady  1245.750        5.0
5   833133           Carrillo Mejia, Jazmin Milagros  1242.750        6.0
6   779653          Espinoza Laime, Sebastian Andree  1223.500        7.0
7   800500        Gutierrez Colan, Diana Lizbeth Mia  1210.375        8.0
8   695798            Huillca Rojas, Estefany Isabel  1210.375        9.0
9   814540                 Soto Yalo, Sharon Marciel  1209.000       10.0
10  715418  Munaylla Huamani, Lorelay Rukmini Kumari  1206.375       11.0
11  844926      Carbajal Piñas, Angellinne Alejandra  1195.500       12.0
12  742601      Aquije Ramirez, Carlos Andres Matias  1193.750       13.0
13  830730        Ordinola Arcelles, Marcelo Esteban  1190.375       14.0
14  688609          Quispe Saldaña, Fabian Alexander  1189.125       15.0
15  702948                  Bacalla Añazco, Patricia  1181.500       16.0
16  728505               Delgado Ramos, Saul Gustavo  1179.375       17.0
17  747457          Salvador Dominguez, Shanie Nikol  1171.250       18.0
18  764184              Gutierrez Atunca, Diego Omar  1168.125       19.0
19  805718        Quiroz Bustamante, Mathias Joaquin  1157.750       20.0
20  731975      Fernandez Zurita, Miyhaki Del Carmen  1155.375       21.0
21  776398           Rodríguez Sánchez, Andrea Lucía  1151.000       22.0
22  691250            Alcalá Torres, Tatiana Valeria  1148.125       23.0
23  817707              Oncoy Ramirez, Jossety Rocio  1130.375       24.0
24  759523             Ventura Conde, Maite Anyelina  1125.750       25.0
25  768502          Alvarez Benites, Lorena Patricia  1119.000       26.0
26  816001       Córdova Castillo, Alessandra Sophia  1117.875       27.0
27  751927           Veliz Portugal, Fabricio Renato  1113.875       28.0
28  758297             Salas Arrieta, Felipe Nicolas  1113.875       29.0
29  730076           Rosales Berrospi, Camila Satomi  1105.875       30.0
30  828550             Anapan Garcia, Nicolle Andrea  1104.750       31.0
31  727263        Hurtado Rosales, Leonor Del Carmen  1099.000       32.0

In [9]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/039/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_conservacion.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/039/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 39 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_conservacion.csv
   39 filas  ×  8 columnas

── Observaciones ──
observacion
ALCANZÓ VACANTE    28
SIN OBSERVACIÓN    11

── Estadísticas de puntaje ──
count      39.000
mean      789.965
std       138.195
min       529.875
25%       692.250
50%       793.250
75%       869.500
max      1075.625

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,754765,"Arevalo Huaman, Steven",CONSERVACIÓN Y RESTAURACIÓN,988.250,4.0,ALCANZÓ VACANTE,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
1,712288,"Arones Allaucca, Jimena Anyeli",CONSERVACIÓN Y RESTAURACIÓN,916.125,6.0,ALCANZÓ VACANTE,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
2,769954,"Beizaga Suarez, Luis Andres",CONSERVACIÓN Y RESTAURACIÓN,970.250,5.0,ALCANZÓ VACANTE,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
3,690104,"Calderon Estumbelo, Glorymar",CONSERVACIÓN Y RESTAURACIÓN,657.125,NaN,SIN OBSERVACIÓN,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
4,812801,"Camacho Leiva, Luis Alexander",CONSERVACIÓN Y RESTAURACIÓN,794.125,19.0,ALCANZÓ VACANTE,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
5,779079,"Castillo Sanchez, Fabricio Alexander",CONSERVACIÓN Y RESTAURACIÓN,691.500,NaN,SIN OBSERVACIÓN,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
6,769349,"Ccanre Taya, Anahi Magdiel",CONSERVACIÓN Y RESTAURACIÓN,793.250,20.0,ALCANZÓ VACANTE,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
7,687544,"Condori Cornejo, Fabricio Aldahier",CONSERVACIÓN Y RESTAURACIÓN,771.875,22.0,ALCANZÓ VACANTE,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
8,741925,"Díaz Olivera, Cielo Mileny",CONSERVACIÓN Y RESTAURACIÓN,855.375,12.0,ALCANZÓ VACANTE,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
9,685829,"Garcia Cabrera, Oriele Alejandra",CONSERVACIÓN Y RESTAURACIÓN,529.875,NaN,SIN OBSERVACIÓN,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
10,702027,"Guerra Mozombite, Farid Steven",CONSERVACIÓN Y RESTAURACIÓN,713.125,27.0,ALCANZÓ VACANTE,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
11,829908,"Huarcaya Baldeon, Shantal Guadalupe",CONSERVACIÓN Y RESTAURACIÓN,743.875,25.0,ALCANZÓ VACANTE,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
12,830654,"Inojosa Gutiérrez, Liz Jennifer",CONSERVACIÓN Y RESTAURACIÓN,839.125,15.0,ALCANZÓ VACANTE,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
13,781476,"Mariluz Aguilar, Isabella Silvana",CONSERVACIÓN Y RESTAURACIÓN,1045.375,3.0,ALCANZÓ VACANTE,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...
14,753522,"Mendoza Cordova, Maria Lucila",CONSERVACIÓN Y RESTAURACIÓN,856.375,11.0,ALCANZÓ VACANTE,CONSERVACIÓN Y RESTAURACIÓN,https://admision.unmsm.edu.pe/Website20262/A/0...

In [10]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_conservacion.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: CONSERVACIÓN Y RESTAURACIÓN
Vacantes obtenidas: 28
Puntaje máximo: 1075.625
Puntaje mínimo: 697.625

    codigo                     apellidos_nombres   puntaje  merito_ep
0   734694      Torres Melendez, Sebastian Isaac  1075.625        1.0
1   687985  Villagaray Trejo, Mariajose Estilita  1075.000        2.0
2   781476     Mariluz Aguilar, Isabella Silvana  1045.375        3.0
3   754765                Arevalo Huaman, Steven   988.250        4.0
4   769954           Beizaga Suarez, Luis Andres   970.250        5.0
5   712288        Arones Allaucca, Jimena Anyeli   916.125        6.0
6   707984      Mesias Perez, Darla Grecia Hazel   911.750        7.0
7   800915         Sanchez Tarazona, Rosa Jazmin   910.625        8.0
8   694731        Rojas Arguelles, Jacory Jimena   886.125        9.0
9   817530             Suarez Anaya, Diego David   882.625       10.0
10  753522         Mendoza Cordova, Maria Lucila   856.375       11.0
11  741925            Díaz Olivera, Cielo Mileny   855.375       12.0
12  697098     Ramos Almanza, Jackeline Milagros   852.375       13.0
13  839864   Valverde Velarde, Alejandra Cecilia   839.250       14.0
14  830654       Inojosa Gutiérrez, Liz Jennifer   839.125       15.0
15  699476       Miranda Mora, Nicole Alessandra   825.250       16.0
16  720843  Sandoval Zapaylle, Abigail Estephany   822.125       17.0
17  786996                     Suica Gomez, Kely   808.625       18.0
18  812801         Camacho Leiva, Luis Alexander   794.125       19.0
19  769349            Ccanre Taya, Anahi Magdiel   793.250       20.0
20  738396      Rumiche Zambrano, Stefany Alexia   775.875       21.0
21  687544    Condori Cornejo, Fabricio Aldahier   771.875       22.0
22  692180          Vega Flores, Neoly Katerinne   766.750       23.0
23  820568   Samaniego Solsol, Rossana Alexandra   752.125       24.0
24  829908   Huarcaya Baldeon, Shantal Guadalupe   743.875       25.0
25  799654          Ochavano Quispe, Maria Jesus   714.000       26.0
26  702027        Guerra Mozombite, Farid Steven   713.125       27.0
27  768571        Soto Meneses, Alisson Michelle   697.625       28.0

In [11]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/111/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_contabilidad.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/111/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 479 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_contabilidad.csv
   479 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          309
ALCANZÓ VACANTE          165
AUSENTE                    4
INHABILITADO (Art. 5)      1

── Estadísticas de puntaje ──
count     475.000
mean      816.174
std       175.550
min       315.250
25%       700.500
50%       810.125
75%       940.875
max      1359.375

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,590867,"Abanto Salazar, Maria Del Carmen",CONTABILIDAD,840.250,NaN,SIN OBSERVACIÓN,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
1,579553,"Acevedo Huallpa, Juluan Anthony",CONTABILIDAD,542.250,NaN,SIN OBSERVACIÓN,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
2,654278,"Acosta Riva, Fernanda Denisse",CONTABILIDAD,787.875,NaN,SIN OBSERVACIÓN,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
3,657451,"Acuña Bolaños, Anai Antuane",CONTABILIDAD,742.125,NaN,SIN OBSERVACIÓN,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
4,648430,"Aguero Chuica, Ellery Fabian",CONTABILIDAD,982.000,79.0,ALCANZÓ VACANTE,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
5,649196,"Aguilar Condori, Damaris Ariasu",CONTABILIDAD,960.000,98.0,ALCANZÓ VACANTE,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
6,647227,"Aguilar Condori, Dayana Milagros",CONTABILIDAD,1039.375,47.0,ALCANZÓ VACANTE,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
7,658833,"Alarcon Asturayme, Yadhira Anabel",CONTABILIDAD,855.000,NaN,SIN OBSERVACIÓN,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
8,650517,"Alarcon Chaupiz, Maria Del Carmen",CONTABILIDAD,1023.375,59.0,ALCANZÓ VACANTE,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
9,560922,"Alberto Flores, Jaime Daniel",CONTABILIDAD,779.875,NaN,SIN OBSERVACIÓN,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
10,578159,"Alcantara Manco, Alonso Fabian",CONTABILIDAD,859.125,NaN,SIN OBSERVACIÓN,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
11,652429,"Alejo Garcia, Diego Alexis",CONTABILIDAD,843.250,NaN,SIN OBSERVACIÓN,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
12,582698,"Alejo Sanchez, Nicolle Reina",CONTABILIDAD,663.625,NaN,SIN OBSERVACIÓN,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
13,649963,"Alfaro Diaz, Alisson Mayte",CONTABILIDAD,1100.750,30.0,ALCANZÓ VACANTE,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...
14,557916,"Aliendres Lagos, Jimena",CONTABILIDAD,758.375,NaN,SIN OBSERVACIÓN,CONTABILIDAD,https://admision.unmsm.edu.pe/Website20262/A/1...

In [12]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_contabilidad.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: CONTABILIDAD
Vacantes obtenidas: 165
Puntaje máximo: 1359.375
Puntaje mínimo: 876.375

     codigo                  apellidos_nombres   puntaje  merito_ep
0    646264        Luna Asian, Fatima Katyuska  1359.375        1.0
1    568722   Gomez Medina, Anggela Mariaelena  1321.125        2.0
2    653507      Cabezas Arango, Miguel Gesebt  1300.000        3.0
3    656081       Guillen Bramon, Joe Leonardo  1290.875        4.0
4    650778    Huaranga Gonzales, Anggela Ruby  1272.000        5.0
..      ...                                ...       ...        ...
160  654440            Mio Najera, David Felix   880.000      161.0
161  592897        Rodriguez Fernández, Carlos   879.375      162.0
162  651356  Rodriguez Ruiz, Ronaile Valentino   878.875      163.0
163  588224     Davila Valencia, Keysi Maritza   877.500      164.0
164  655147   Puente Vilcamichi, Mauro Snayder   876.375      165.0

[165 rows x 4 columns]

In [13]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/115/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_criminalistica.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/115/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 168 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_criminalistica.csv
   168 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          121
ALCANZÓ VACANTE           45
AUSENTE                    1
INHABILITADO (Art. 5)      1

── Estadísticas de puntaje ──
count     167.000
mean      777.687
std       149.072
min       453.875
25%       668.312
50%       770.750
75%       855.750
max      1132.125

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,652518,"Abregu Tipacti, Anibal Guillermo",CRIMINALÍSTICA FINANCIERA FORENSE,NaN,NaN,AUSENTE,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
1,588198,"Aguilar Garcia, Karol Camila",CRIMINALÍSTICA FINANCIERA FORENSE,775.875,NaN,SIN OBSERVACIÓN,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
2,650615,"Aguilar Paucar, Fabricio Leandro",CRIMINALÍSTICA FINANCIERA FORENSE,810.125,NaN,SIN OBSERVACIÓN,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
3,652607,"Aguilar Zamora, Mateo Enrique",CRIMINALÍSTICA FINANCIERA FORENSE,641.125,NaN,SIN OBSERVACIÓN,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
4,554818,"Agurto Rosario, Bily Esmit",CRIMINALÍSTICA FINANCIERA FORENSE,623.375,NaN,SIN OBSERVACIÓN,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
5,551546,"Almeyda Saravia, Cinthya Mariela",CRIMINALÍSTICA FINANCIERA FORENSE,862.000,39.0,ALCANZÓ VACANTE,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
6,645800,"Alvarado Mamani, Dulce Luciana Thalia",CRIMINALÍSTICA FINANCIERA FORENSE,835.250,NaN,SIN OBSERVACIÓN,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
7,592397,"Alvarez Melchor, Lucero Leonela",CRIMINALÍSTICA FINANCIERA FORENSE,726.750,NaN,SIN OBSERVACIÓN,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
8,649427,"Alvarez Tocto, Gustavo Fernando",CRIMINALÍSTICA FINANCIERA FORENSE,708.500,NaN,SIN OBSERVACIÓN,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
9,570760,"Amoroto Rojas, Freyhtzzy Yanely",CRIMINALÍSTICA FINANCIERA FORENSE,682.500,NaN,SIN OBSERVACIÓN,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
10,657066,"Angeles Tarazona, Nayeli Nicole",CRIMINALÍSTICA FINANCIERA FORENSE,718.750,NaN,SIN OBSERVACIÓN,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
11,550450,"Aquino Champi, Nayely Lucero",CRIMINALÍSTICA FINANCIERA FORENSE,653.125,NaN,SIN OBSERVACIÓN,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
12,654463,"Arana Trinidad, Brayan Anthony",CRIMINALÍSTICA FINANCIERA FORENSE,974.000,24.0,ALCANZÓ VACANTE,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
13,552632,"Aranibar Cadillo, Marcelo Franco",CRIMINALÍSTICA FINANCIERA FORENSE,683.375,NaN,SIN OBSERVACIÓN,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...
14,582780,"Arela Utus, Arlyn",CRIMINALÍSTICA FINANCIERA FORENSE,498.250,NaN,SIN OBSERVACIÓN,CRIMINALÍSTICA FINANCIERA FORENSE,https://admision.unmsm.edu.pe/Website20262/A/1...

In [15]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_criminalistica.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: CRIMINALÍSTICA FINANCIERA FORENSE
Vacantes obtenidas: 45
Puntaje máximo: 1132.125
Puntaje mínimo: 854.625

    codigo                       apellidos_nombres   puntaje  merito_ep
0   649566        Zamudio Reyes, Xiomara Geraldine  1132.125        1.0
1   656523          Cardenas Parian, Alexia Mariel  1119.000        2.0
2   568840              Garcia Asturay, Eva Ariana  1097.625        3.0
3   575886            Aybar Mitac, Lionel Salvador  1090.875        4.0
4   653123        Vargas Requena, Fabricio Gabriel  1069.500        5.0
5   646616          Manrique Flores, Marcel Ramiro  1062.500        6.0
6   655345            Zelaya Navarro, Frank Xavier  1062.500        7.0
7   590303                  Nolasco Ojeda, Heisser  1058.500        8.0
8   576607  Castañeda Quillo, Marco Antonio Urbano  1057.250        9.0
9   657370      Montano Coronel, Leonor Del Carmen  1040.250       10.0
10  653612           Rojas Gamarra, Coraly Mariana  1029.750       11.0
11  586216            Vilela Ramon, Yuleimy Karina  1008.750       12.0
12  649247        Fernandez Padilla, Andrea Sharon  1005.375       13.0
13  657529           Barrios Maturrano, John Jairo  1003.000       14.0
14  589548      Carhuapoma Fano, Elizabeth Antonia  1001.875       15.0
15  656529      Rodriguez Badillo, Milenka Jazmine   998.875       16.0
16  652815              Torres Quilca, Diego Frank   995.125       17.0
17  654152                Taipe Llasacce, Milagros   991.125       18.0
18  590447            Montoya Montero, Yadira Kate   988.125       19.0
19  659391       Colonia Martinez, Xiomara Jessica   983.125       20.0
20  647466            Eusebio Machaca, Dante Pavel   981.125       21.0
21  656733            Paucar Huamani, Climer Yordy   978.500       22.0
22  653252            Arevalo Alarcon, Hernan Joel   975.125       23.0
23  654463          Arana Trinidad, Brayan Anthony   974.000       24.0
24  650823          Morales Chimpen, Damarys Luana   968.250       25.0
25  654053        Siguayro Arevalo, Nayella Isabel   956.875       26.0
26  659701       Torvisco Vasquez, Mariel Fernanda   951.125       27.0
27  649746           Ramirez Vivas, Tatiana Nicole   941.375       28.0
28  649976           Serquin Calle, Adrian Eduardo   925.375       29.0
29  588602         Mendoza Gamboa, Madeley Xiomara   919.750       30.0
30  656990            Bolaños Mejia, Franco Alonso   918.625       31.0
31  651311            Aylas Guevara, Elvis Ricardo   915.750       32.0
32  573715             Ramos Martin, Yasmany Hasan   911.125       33.0
33  647281              Torres Quispe, Anna Raquel   902.625       34.0
34  647247                Peña Reyes, Carlos Isaac   897.500       35.0
35  649335              Dextre Malo, Johnn Adriano   886.625       36.0
36  590568         Huamani Guerrero, Kahory Ayelen   873.500       37.0
37  645147        Benavides Pacheco, Jose Santiago   872.375       38.0
38  551546        Almeyda Saravia, Cinthya Mariela   862.000       39.0
39  551906                Estrada Gomez, Alexandra   861.500       40.0
40  582612         Huamani Reategui, Joan Wilfredo   860.375       41.0
41  654522            Leandro Yana, Carlos Gabriel   855.125       42.0
42  647124      Zimmermann Medina, Fabiana Eduarda   855.000       43.0
43  584655           Gomez Suclupe, Brillit Pamela   854.875       44.0
44  651216           Chipana Bautista, Anna Nicole   854.625       45.0

In [16]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/022/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_derecho.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/022/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 1873 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_derecho.csv
   1873 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          1689
ALCANZÓ VACANTE           140
INHABILITADO (Art. 5)      25
AUSENTE                    19

── Estadísticas de puntaje ──
count    1854.000
mean      888.031
std       204.145
min       148.625
25%       739.250
50%       886.875
75%      1031.531
max      1638.000

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,728518,"Abad Tabara, Valery Nicole",DERECHO,912.625,NaN,SIN OBSERVACIÓN,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
1,709843,"Abado Cordova, Lin Wendy Viviana",DERECHO,726.750,NaN,SIN OBSERVACIÓN,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
2,763699,"Acevedo Rojas, Jade Samira",DERECHO,1198.375,119.0,ALCANZÓ VACANTE,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
3,698962,"Acosta Estrella, Adriana Patricia",DERECHO,803.375,NaN,SIN OBSERVACIÓN,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
4,745347,"Acosta Lopez, Fabrizio Sebastian",DERECHO,1003.125,NaN,SIN OBSERVACIÓN,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
5,756099,"Acuña Vargas, Richard Alex",DERECHO,1504.375,2.0,ALCANZÓ VACANTE,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
6,703742,"Aguedo Cirilo, Rodrigo Lucas",DERECHO,1300.000,37.0,ALCANZÓ VACANTE,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
7,760490,"Aguilar Facundo, Leandro Enrique",DERECHO,975.125,NaN,SIN OBSERVACIÓN,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
8,762286,"Aguilar Matos, Luhanna Aydee Pamela",DERECHO,655.250,NaN,SIN OBSERVACIÓN,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
9,733028,"Aguilar Montoya, Mirella",DERECHO,935.625,NaN,SIN OBSERVACIÓN,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
10,740133,"Aguilar Rojas, Bruno Favio",DERECHO,902.625,NaN,SIN OBSERVACIÓN,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
11,727929,"Aguirre Hidalgo, Xiomara Betsabe",DERECHO,665.000,NaN,SIN OBSERVACIÓN,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
12,783875,"Aguirre Mallqui, Elizabet",DERECHO,912.125,NaN,SIN OBSERVACIÓN,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
13,705132,"Aguirre Montalvo, Nadia Aracely",DERECHO,876.875,NaN,SIN OBSERVACIÓN,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...
14,836891,"Alagon Pumayauli, Estrellita Kristell",DERECHO,615.750,NaN,SIN OBSERVACIÓN,DERECHO,https://admision.unmsm.edu.pe/Website20262/A/0...

In [17]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_derecho.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: DERECHO
Vacantes obtenidas: 140
Puntaje máximo: 1638.0
Puntaje mínimo: 1186.375

     codigo                      apellidos_nombres   puntaje  merito_ep
0    824014            Espinoza Rojas, Gino Daniel  1638.000        1.0
1    756099             Acuña Vargas, Richard Alex  1504.375        2.0
2    831946        Minaya Serra, Solange Christell  1504.375        3.0
3    776466        Rosales Cuya, Ricardo Sebastian  1502.125        4.0
4    800587     Au Yeung Zevallos, Angelo Fabrizio  1485.000        5.0
..      ...                                    ...       ...        ...
135  842786         Cosco Wilcamango, Nadya Sarahi  1189.250      137.0
136  830748  Llacsahuanga Cortez, Zuleyka Dayanara  1189.250      136.0
137  698624         Rebata Ochante, Fernanda Tahis  1188.500      138.0
138  720176           Vivar Ocsas, Luciana Noreliz  1187.500      139.0
139  740495           Perez De La Cruz, Cesia Ruth  1186.375      140.0

[140 rows x 4 columns]

In [18]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/121/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_economia.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/121/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 659 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_economia.csv
   659 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          565
ALCANZÓ VACANTE           79
AUSENTE                    8
INHABILITADO (Art. 5)      7

── Estadísticas de puntaje ──
count     651.000
mean      901.060
std       196.627
min       307.750
25%       758.375
50%       897.500
75%      1026.500
max      1545.500

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,654905,"Abanto Diaz, Cristofer Saulito",ECONOMÍA,956.875,NaN,SIN OBSERVACIÓN,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
1,583738,"Abanto Vega, Ruben Andersson",ECONOMÍA,1202.375,49.0,ALCANZÓ VACANTE,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
2,646288,"Abarca Rosas, Jhoan Pierce",ECONOMÍA,914.625,NaN,SIN OBSERVACIÓN,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
3,648321,"Abele Farfán, Astrid Josefina",ECONOMÍA,832.375,NaN,SIN OBSERVACIÓN,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
4,645737,"Acosta Mori, Leonela Victoria",ECONOMÍA,843.875,NaN,SIN OBSERVACIÓN,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
5,579272,"Advincula Damacio, Julio Cesar",ECONOMÍA,663.375,NaN,SIN OBSERVACIÓN,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
6,645236,"Afuso Morales, Luss De Los Angeles",ECONOMÍA,872.375,NaN,SIN OBSERVACIÓN,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
7,555062,"Aguilar Zevallos, Lucas Samuel",ECONOMÍA,1253.125,25.0,ALCANZÓ VACANTE,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
8,659343,"Aguirre Huyhua, Joshua Mathias",ECONOMÍA,1253.750,23.0,ALCANZÓ VACANTE,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
9,659111,"Alarcon Llactas, Jean Franco",ECONOMÍA,576.000,NaN,SIN OBSERVACIÓN,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
10,568572,"Albino Rosillo, Paolo Enrique Lorenzo",ECONOMÍA,1196.000,52.0,ALCANZÓ VACANTE,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
11,655348,"Aldazabal Gonzales, Gustavo Eduardo",ECONOMÍA,768.750,NaN,SIN OBSERVACIÓN,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
12,586821,"Alegria Rojas, Karim K.",ECONOMÍA,847.250,NaN,SIN OBSERVACIÓN,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
13,653739,"Alejandro Suarez, Henry Fernando",ECONOMÍA,513.250,NaN,SIN OBSERVACIÓN,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...
14,550160,"Alejo Reyes, Jhon Porfirio",ECONOMÍA,1043.875,NaN,SIN OBSERVACIÓN,ECONOMÍA,https://admision.unmsm.edu.pe/Website20262/A/1...

In [19]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_economia.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: ECONOMÍA
Vacantes obtenidas: 79
Puntaje máximo: 1545.5
Puntaje mínimo: 1148.125

    codigo                        apellidos_nombres   puntaje  merito_ep
0   653467  Heredia Mendoza, Alexander Paolo Victor  1545.500        1.0
1   551813             Torres Pozo, Mauricio Rafael  1481.000        2.0
2   649678          Puican Aldoradin, Rodrigo Jorge  1455.875        3.0
3   657179          Chambilla Vilca, Frank Emmanuel  1414.750        4.0
4   651751         Hermoza Cabellos, Johnny Antonio  1390.125        5.0
..     ...                                      ...       ...        ...
74  655231    Medina Nicho, Joaquín Andrée Leonardo  1150.375       74.0
75  581267              Docto Shica, Angel Anderson  1149.250       77.0
76  652868         Sánchez Flores, Leonardo Gabriel  1149.250       76.0
77  564376           Lino Jimenez, Nicole Alexandra  1148.125       79.0
78  589108    Escalante Davila, Gianpiero Alexandre  1148.125       78.0

[79 rows x 4 columns]

In [20]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/123/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_ecointer.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/123/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 311 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_ecointer.csv
   311 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          222
ALCANZÓ VACANTE           84
INHABILITADO (Art. 5)      4
AUSENTE                    1

── Estadísticas de puntaje ──
count     310.000
mean      887.320
std       181.114
min       445.875
25%       739.844
50%       883.188
75%      1015.781
max      1405.625

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,654560,"Aguedo Loayza, Luis Adolfo De Jesús",ECONOMÍA INTERNACIONAL,962.000,NaN,SIN OBSERVACIÓN,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
1,651061,"Aguilar Gálvez, Edson Alexandro",ECONOMÍA INTERNACIONAL,719.250,NaN,SIN OBSERVACIÓN,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
2,645368,"Albinagorta Ruidias, Leonel Aaron",ECONOMÍA INTERNACIONAL,807.250,NaN,SIN OBSERVACIÓN,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
3,652923,"Alca Sanchez, Noemi",ECONOMÍA INTERNACIONAL,747.875,NaN,SIN OBSERVACIÓN,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
4,594381,"Alcala Triviños, Luis Angel",ECONOMÍA INTERNACIONAL,835.250,NaN,SIN OBSERVACIÓN,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
5,566689,"Ali Rojas, Andry Alexander",ECONOMÍA INTERNACIONAL,907.750,NaN,SIN OBSERVACIÓN,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
6,586808,"Altamiza Gonzales, Evans Exal",ECONOMÍA INTERNACIONAL,1054.500,54.0,ALCANZÓ VACANTE,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
7,583384,"Alva Cadillo, Arianna",ECONOMÍA INTERNACIONAL,1144.125,28.0,ALCANZÓ VACANTE,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
8,651434,"Alvarez Velasquez, Sebastián Imanol",ECONOMÍA INTERNACIONAL,876.875,NaN,SIN OBSERVACIÓN,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
9,654565,"Anaya Bojórquez, Valeri Alexandra",ECONOMÍA INTERNACIONAL,661.125,NaN,SIN OBSERVACIÓN,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
10,651177,"Andia Sosa, Anthony Cesar",ECONOMÍA INTERNACIONAL,658.750,NaN,SIN OBSERVACIÓN,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
11,587164,"Antayhua Ramirez, Andy Jesus",ECONOMÍA INTERNACIONAL,955.125,NaN,SIN OBSERVACIÓN,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
12,652129,"Aquino Quispe, Ana Paola",ECONOMÍA INTERNACIONAL,1036.750,68.0,ALCANZÓ VACANTE,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
13,652673,"Aquino Sulca, Jhonatan Adriano",ECONOMÍA INTERNACIONAL,705.625,NaN,SIN OBSERVACIÓN,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...
14,654248,"Aquituari Pashanaste, Daniel Antonio",ECONOMÍA INTERNACIONAL,776.875,NaN,SIN OBSERVACIÓN,ECONOMÍA INTERNACIONAL,https://admision.unmsm.edu.pe/Website20262/A/1...

In [21]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_ecointer.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: ECONOMÍA INTERNACIONAL
Vacantes obtenidas: 84
Puntaje máximo: 1405.625
Puntaje mínimo: 1009.375

    codigo                    apellidos_nombres   puntaje  merito_ep
0   592477            Risco Santiago, Alejandro  1405.625        1.0
1   652462            Rojas Nario, Julio Javier  1401.000        2.0
2   653919  Pomahuallca Guerrera, Anahi Yadhira  1306.250        3.0
3   594730       Minaya Huacho, Sebastian Aaron  1300.000        4.0
4   658715     Ballena Espinoza, Marcelo Alonso  1261.750        5.0
..     ...                                  ...       ...        ...
79  654456      Caceres Pancorbo, Sergio Alonso  1013.250       80.0
80  659347          Pipa Delgado, Jesús Roberto  1012.125       81.0
81  647999             Callan Reyes, Kevin Luis  1011.000       82.0
82  648351     Jimenez Florencio, Denis Francis  1009.375       84.0
83  566751      Hormaza Rojas, Fiorella Biviana  1009.375       83.0

[84 rows x 4 columns]

In [22]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/122/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_ecopubli.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/122/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 174 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_ecopubli.csv
   174 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          89
ALCANZÓ VACANTE          83
INHABILITADO (Art. 5)     2

── Estadísticas de puntaje ──
count     174.000
mean      888.112
std       167.917
min       482.500
25%       770.000
50%       886.875
75%      1004.969
max      1356.375

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,649472,"Adanaque Salazar, Jostin Samir",ECONOMÍA PÚBLICA,674.250,NaN,SIN OBSERVACIÓN,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
1,659882,"Aguinaga Rodriguez, Daniela Fernanda",ECONOMÍA PÚBLICA,979.125,48.0,ALCANZÓ VACANTE,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
2,656423,"Alarcon Castro, Jenifer Yesenia",ECONOMÍA PÚBLICA,872.500,NaN,SIN OBSERVACIÓN,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
3,592996,"Alarcon Pflucker, Hanssel Alejandro",ECONOMÍA PÚBLICA,771.875,NaN,SIN OBSERVACIÓN,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
4,653918,"Aller Julca, Yameli Cristina",ECONOMÍA PÚBLICA,982.500,47.0,ALCANZÓ VACANTE,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
5,645361,"Andagua Centeno, Jesus Augusto",ECONOMÍA PÚBLICA,966.000,52.0,ALCANZÓ VACANTE,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
6,646665,"Angeles Pezo, Ailyn Sun",ECONOMÍA PÚBLICA,836.375,NaN,SIN OBSERVACIÓN,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
7,655146,"Antezana Vera, Gian Christian",ECONOMÍA PÚBLICA,1107.000,14.0,ALCANZÓ VACANTE,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
8,648826,"Anyosa Castañeda, Samuel Leonardo",ECONOMÍA PÚBLICA,876.375,NaN,SIN OBSERVACIÓN,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
9,583508,"Apfata Taipe, Josue Fernando",ECONOMÍA PÚBLICA,992.250,46.0,ALCANZÓ VACANTE,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
10,575184,"Araujo Peña, Abigail Yamile",ECONOMÍA PÚBLICA,719.750,NaN,SIN OBSERVACIÓN,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
11,646178,"Aroste Huayllas, Nicole",ECONOMÍA PÚBLICA,776.250,NaN,SIN OBSERVACIÓN,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
12,649226,"Arteaga Vigo, Andres Joaquin",ECONOMÍA PÚBLICA,1097.875,19.0,ALCANZÓ VACANTE,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
13,653626,"Aysa Quispe, William Felix",ECONOMÍA PÚBLICA,755.250,NaN,SIN OBSERVACIÓN,ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...
14,573212,"Baez Villavicencio, Frank Jacomo",ECONOMÍA PÚBLICA,1061.875,NaN,INHABILITADO (Art. 5),ECONOMÍA PÚBLICA,https://admision.unmsm.edu.pe/Website20262/A/1...

In [23]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_ecopubli.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: ECONOMÍA PÚBLICA
Vacantes obtenidas: 83
Puntaje máximo: 1356.375
Puntaje mínimo: 900.875

    codigo                  apellidos_nombres   puntaje  merito_ep
0   557551  Vega Gonzales, Gianpool Sebastian  1356.375        1.0
1   581367      Vasquez Corman, Wiliam Adrian  1326.250        2.0
2   570289   Rosales Torres, Alessandro Carlo  1302.125        3.0
3   556156    Jares Guevara, Ariel Franchesco  1257.125        4.0
4   566142    Canales Flores, Carla Elizabeth  1224.625        5.0
..     ...                                ...       ...        ...
78  650496     Vega Castillo, Sebastian Kevin   906.625       78.0
79  653261     Urbano Dominguez, Daniel Niles   906.625       79.0
80  654786     Serna Vega, Gabriela Alexandra   904.875       81.0
81  652324    Quicaño Aguirre, Mayara Adriana   900.875       82.0
82  574027     Ñiquen Mejia, Cristhian Rafael   900.875       83.0

[83 rows x 4 columns]

In [24]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/062/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_edfisica.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/062/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 160 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_edfisica.csv
   160 filas  ×  8 columnas

── Observaciones ──
observacion
ALCANZÓ VACANTE          95
SIN OBSERVACIÓN          63
INHABILITADO (Art. 5)     1
AUSENTE                   1

── Estadísticas de puntaje ──
count     159.000
mean      934.754
std       126.880
min       595.005
25%       845.448
50%       928.967
75%      1032.438
max      1248.171

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,832308,"Abal Hilario, Armando Fabián",EDUCACIÓN FÍSICA,1050.326,32.0,ALCANZÓ VACANTE,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
1,729705,"Acevedo Baca, Alejandro Nicolas",EDUCACIÓN FÍSICA,966.942,64.0,ALCANZÓ VACANTE,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
2,829451,"Agurto Salazar, Angelo Abraham",EDUCACIÓN FÍSICA,871.550,NaN,SIN OBSERVACIÓN,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
3,817144,"Alania Atavillos, Edilson Roger",EDUCACIÓN FÍSICA,707.205,NaN,SIN OBSERVACIÓN,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
4,829672,"Alavena Eyzaguirre, Stefano Rolando",EDUCACIÓN FÍSICA,856.121,NaN,SIN OBSERVACIÓN,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
5,807096,"Aliaga Torres, Juan Pablo Gabriel",EDUCACIÓN FÍSICA,1078.150,23.0,ALCANZÓ VACANTE,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
6,780965,"Alva Pecca, Ronel Franco",EDUCACIÓN FÍSICA,1072.225,27.0,ALCANZÓ VACANTE,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
7,716990,"Alvarez Dongo, Jeampiers",EDUCACIÓN FÍSICA,832.634,NaN,SIN OBSERVACIÓN,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
8,686533,"Alvis Vargas, Pedro Fabiano",EDUCACIÓN FÍSICA,974.888,59.0,ALCANZÓ VACANTE,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
9,787629,"Andia Paqui, Ysmael Mateo",EDUCACIÓN FÍSICA,896.496,94.0,ALCANZÓ VACANTE,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
10,699847,"Aranguri Ruiz, Danny Fabián",EDUCACIÓN FÍSICA,844.796,NaN,SIN OBSERVACIÓN,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
11,735030,"Arroyo Alva, Hector Andre",EDUCACIÓN FÍSICA,973.433,60.0,ALCANZÓ VACANTE,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
12,707980,"Atencia Aguilar, Piero Angelo",EDUCACIÓN FÍSICA,969.563,62.0,ALCANZÓ VACANTE,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
13,779147,"Barahona Indacochea, Josue Lionell",EDUCACIÓN FÍSICA,831.746,NaN,SIN OBSERVACIÓN,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...
14,755473,"Barra Ormeño, Alexa Thamara",EDUCACIÓN FÍSICA,884.162,NaN,SIN OBSERVACIÓN,EDUCACIÓN FÍSICA,https://admision.unmsm.edu.pe/Website20262/A/0...

In [25]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_edfisica.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: EDUCACIÓN FÍSICA
Vacantes obtenidas: 95
Puntaje máximo: 1248.171
Puntaje mínimo: 896.262

    codigo                  apellidos_nombres   puntaje  merito_ep
0   814284        Ramírez Ramos, Jostin Slash  1248.171        1.0
1   708761      Medrano Berrios, Aaron Javier  1239.250        2.0
2   723675  Gonzales Acosta, Joaquin Albhieri  1172.226        3.0
3   694303       Bermudo Pérez, Jairo Josafat  1152.763        4.0
4   788667     Santiago Santiago, Viviana Luz  1152.188        5.0
..     ...                                ...       ...        ...
90  728955         Cieza Quintana, Kati Paola   905.875       91.0
91  711140      Montero Cueva, Vieri Giovanny   904.237       92.0
92  729146          Rivas Ccoicca, Omar Dante   900.292       93.0
93  787629          Andia Paqui, Ysmael Mateo   896.496       94.0
94  733884   Curipuma Mauricio, Danilo Moises   896.262       95.0

[95 rows x 4 columns]

In [26]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/0611/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_edinicial.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/0611/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 179 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_edinicial.csv
   179 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          159
ALCANZÓ VACANTE           18
INHABILITADO (Art. 5)      2

── Estadísticas de puntaje ──
count     179.000
mean      727.158
std       148.385
min       362.500
25%       627.938
50%       713.750
75%       832.688
max      1108.125

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,751643,"Achulli Valeriano, Flor Milagros",EDUCACIÓN INICIAL,668.375,NaN,SIN OBSERVACIÓN,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
1,747979,"Acosta Herrera, Patricia Alexandra",EDUCACIÓN INICIAL,798.375,NaN,SIN OBSERVACIÓN,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
2,797640,"Alcazar Lopez, Ximena",EDUCACIÓN INICIAL,924.875,18.0,ALCANZÓ VACANTE,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
3,828804,"Aldunate Cabanillas, Jimena Qoricollor",EDUCACIÓN INICIAL,689.875,NaN,SIN OBSERVACIÓN,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
4,818591,"Anaya Perez, Ayelen Xiomara",EDUCACIÓN INICIAL,507.500,NaN,SIN OBSERVACIÓN,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
5,695732,"Andia Quispe, Jennevike Massiel",EDUCACIÓN INICIAL,746.750,NaN,SIN OBSERVACIÓN,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
6,840744,"Antaurco Aragón, Elizabeth Salomé",EDUCACIÓN INICIAL,799.625,NaN,SIN OBSERVACIÓN,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
7,840547,"Antunez Alvarez, Alison Regina",EDUCACIÓN INICIAL,889.875,NaN,SIN OBSERVACIÓN,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
8,694716,"Aponte Quispe, Melissa Emily",EDUCACIÓN INICIAL,683.000,NaN,SIN OBSERVACIÓN,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
9,788517,"Ardiles Zavaleta, Maricielo",EDUCACIÓN INICIAL,562.250,NaN,SIN OBSERVACIÓN,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
10,793156,"Arias Berrocal, Maria Dionisia",EDUCACIÓN INICIAL,704.500,NaN,SIN OBSERVACIÓN,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
11,694428,"Arispe De La Cruz, Esmeralda Camila",EDUCACIÓN INICIAL,779.750,NaN,SIN OBSERVACIÓN,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
12,835013,"Arotoma Ichpas, Flor De Maria",EDUCACIÓN INICIAL,843.250,NaN,SIN OBSERVACIÓN,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
13,793961,"Arriaga Mamani, Esther",EDUCACIÓN INICIAL,935.125,15.0,ALCANZÓ VACANTE,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...
14,751177,"Ascona Diaz, Luciana Maythe",EDUCACIÓN INICIAL,601.625,NaN,SIN OBSERVACIÓN,EDUCACIÓN INICIAL,https://admision.unmsm.edu.pe/Website20262/A/0...

In [27]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_edinicial.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: EDUCACIÓN INICIAL
Vacantes obtenidas: 18
Puntaje máximo: 1108.125
Puntaje mínimo: 924.875

    codigo                       apellidos_nombres   puntaje  merito_ep
0   703991  Malasquez Llacsahuanga, Andrea Cosette  1108.125        1.0
1   690262          Huayanay Adán, Medaly Estefany  1091.000        2.0
2   822218          Pizarro Cabrera, Rubi Kimberly  1041.375        3.0
3   753605               Romero Arce, Selene Maria  1034.375        4.0
4   687155      Portilla Inca, Massyell Cielo Yuri  1028.000        5.0
5   693010      Mantari Ochante, Gianella Milagros  1020.250        6.0
6   760311           Castillo Carrero, Jhoana Lian   987.125        7.0
7   686673         Rivera Centurión, Rihana Nahomy   978.000        8.0
8   844772       Panduro Cardenas, Brisa Alejandra   975.500        9.0
9   694203                Luque Felix, Karla Sofía   974.000       10.0
10  688287          Calderon Perez, Fabiana Ximena   970.000       11.0
11  768184                Lopez Ponte, Nicol Ashly   960.625       12.0
12  706784     Gamarra Hinostroza, Yeritzel Ximena   956.250       13.0
13  719707               Moro Conca, Yasuri Isabel   936.250       14.0
14  793961                  Arriaga Mamani, Esther   935.125       15.0
15  838560        Velasquez Cruz, Dannae Alejandra   931.750       16.0
16  828958     Cornejo Benavides, Grecia Alexandra   926.000       17.0
17  797640                   Alcazar Lopez, Ximena   924.875       18.0

In [28]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/0612/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_edprimaria.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/0612/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 146 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_edprimaria.csv
   146 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN    126
ALCANZÓ VACANTE     20

── Estadísticas de puntaje ──
count     146.000
mean      792.002
std       166.403
min       384.625
25%       680.094
50%       788.625
75%       902.938
max      1267.375

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,741106,"Acco Ludena, Stefano Gadiel",EDUCACIÓN PRIMARIA,759.250,NaN,SIN OBSERVACIÓN,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
1,740655,"Acho Sanchez, Naydely Alexia",EDUCACIÓN PRIMARIA,746.750,NaN,SIN OBSERVACIÓN,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
2,724537,"Alvarez Gomez, Camila Maricel",EDUCACIÓN PRIMARIA,787.250,NaN,SIN OBSERVACIÓN,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
3,726843,"Antaurco Sucasaire, Kiara Grecia",EDUCACIÓN PRIMARIA,782.000,NaN,SIN OBSERVACIÓN,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
4,749535,"Anyosa Tumpay, Aracely Raquel",EDUCACIÓN PRIMARIA,951.625,NaN,SIN OBSERVACIÓN,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
5,690021,"Araujo Tito, Jannira Anahí",EDUCACIÓN PRIMARIA,740.125,NaN,SIN OBSERVACIÓN,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
6,755862,"Arroyo Martinez, Esmeralda Sofia",EDUCACIÓN PRIMARIA,704.875,NaN,SIN OBSERVACIÓN,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
7,801004,"Asencio Ochoa, Nicoll Cristina",EDUCACIÓN PRIMARIA,877.500,NaN,SIN OBSERVACIÓN,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
8,690583,"Atalaya Valentino, Betzabe Min",EDUCACIÓN PRIMARIA,1267.375,1.0,ALCANZÓ VACANTE,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
9,830252,"Atencia Caja, Milagros Nicole",EDUCACIÓN PRIMARIA,687.375,NaN,SIN OBSERVACIÓN,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
10,817316,"Baca Huaraca, Cielo Dayana",EDUCACIÓN PRIMARIA,733.625,NaN,SIN OBSERVACIÓN,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
11,841346,"Bada Paucar, Noemi Betsabe",EDUCACIÓN PRIMARIA,975.125,NaN,SIN OBSERVACIÓN,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
12,824612,"Barrios Lapa, Maria Fernanda",EDUCACIÓN PRIMARIA,558.000,NaN,SIN OBSERVACIÓN,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
13,844356,"Bolangger Montes, Elizabeth Victoria",EDUCACIÓN PRIMARIA,1027.375,12.0,ALCANZÓ VACANTE,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
14,822538,"Bustamante Iparraguirre, Valeria Sofia",EDUCACIÓN PRIMARIA,841.375,NaN,SIN OBSERVACIÓN,EDUCACIÓN PRIMARIA,https://admision.unmsm.edu.pe/Website20262/A/0...

In [29]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_edprimaria.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: EDUCACIÓN PRIMARIA
Vacantes obtenidas: 20
Puntaje máximo: 1267.375
Puntaje mínimo: 981.75

    codigo                      apellidos_nombres   puntaje  merito_ep
0   690583         Atalaya Valentino, Betzabe Min  1267.375        1.0
1   795076       Machuca Reymundo, Mayori Betsabe  1137.750        2.0
2   720710     Salluca Huahualuque, Mitzu Alisson  1137.125        3.0
3   723678            Castro Garcia, Gady Milissa  1093.250        4.0
4   722811                 Laura Laura, Mía Qanka  1087.375        5.0
5   826044      Lloclla Salazar, Adriana Carolina  1076.500        6.0
6   687244     Olivera Auccatinco, Nicolle Angely  1060.750        7.0
7   795570                  Calle Ccoa, Francesca  1054.500        8.0
8   756178  Vales Misajel, Jany Mercedes Karolina  1047.625        9.0
9   753608         Villa Portilla, Maria Milagros  1044.750       10.0
10  832375         Ullilen Orozco, Arianna Yamile  1040.750       11.0
11  844356   Bolangger Montes, Elizabeth Victoria  1027.375       12.0
12  697110        Naupari Ventura, Aracely Rebeca  1026.500       13.0
13  814047     Olortegui Sevillano, Deyci Fiorela  1022.500       14.0
14  823891       Urbina Suarez, Nayeli Alessandra  1018.375       15.0
15  740312       Coronado Castillo, Marco Stefano  1004.250       16.0
16  721479           Ramos Correa, Priscila Anahi  1000.250       17.0
17  711784        Jacobe Salcedo, Angela Estrella   993.375       18.0
18  794490            Flores Flores, Diana Ximena   982.500       19.0
19  813679        Collado Huaraka, Dominic Matias   981.750       20.0

In [30]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/0613/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_edsecundaria.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/0613/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 361 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_edsecundaria.csv
   361 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN    282
ALCANZÓ VACANTE     76
AUSENTE              3

── Estadísticas de puntaje ──
count     358.000
mean      830.826
std       172.308
min       375.625
25%       721.188
50%       833.188
75%       949.500
max      1371.375

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,732432,"Abrego Bonifacio, Brisa Anyeli",EDUCACIÓN SECUNDARIA,809.000,NaN,SIN OBSERVACIÓN,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
1,842324,"Acuña Gamarra, Isabel Alexandra",EDUCACIÓN SECUNDARIA,695.500,NaN,SIN OBSERVACIÓN,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
2,832751,"Adriano Valencia, Luz Bella",EDUCACIÓN SECUNDARIA,894.625,NaN,SIN OBSERVACIÓN,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
3,829820,"Aguirre Mendoza, Brilly Carolina",EDUCACIÓN SECUNDARIA,979.125,68.0,ALCANZÓ VACANTE,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
4,768731,"Aguirre Monzón, Maria Isabel Yamileth",EDUCACIÓN SECUNDARIA,753.500,NaN,SIN OBSERVACIÓN,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
5,800856,"Aguirre Rivera, Valery Arlette",EDUCACIÓN SECUNDARIA,763.500,NaN,SIN OBSERVACIÓN,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
6,717716,"Aguirre Wall, Franshesco Dominic",EDUCACIÓN SECUNDARIA,832.000,NaN,SIN OBSERVACIÓN,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
7,691149,"Alania Vargas, Trayce Nicol",EDUCACIÓN SECUNDARIA,580.250,NaN,SIN OBSERVACIÓN,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
8,745653,"Alarcon Baez, Ronald",EDUCACIÓN SECUNDARIA,1021.375,47.0,ALCANZÓ VACANTE,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
9,800890,"Aldazabal Cruz, Noelia Sayuri",EDUCACIÓN SECUNDARIA,506.375,NaN,SIN OBSERVACIÓN,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
10,831547,"Allauca Torres, Andy Dubal",EDUCACIÓN SECUNDARIA,978.000,71.0,ALCANZÓ VACANTE,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
11,799397,"Almanza Damian, Giuliana Melissa",EDUCACIÓN SECUNDARIA,1062.500,28.0,ALCANZÓ VACANTE,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
12,752097,"Alva Alba, Nain Gabriel",EDUCACIÓN SECUNDARIA,1371.375,1.0,ALCANZÓ VACANTE,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
13,766879,"Alva Muñoz, Lucero Sumac",EDUCACIÓN SECUNDARIA,837.250,NaN,SIN OBSERVACIÓN,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...
14,821883,"Alva Murillo, Viany Meylin",EDUCACIÓN SECUNDARIA,847.250,NaN,SIN OBSERVACIÓN,EDUCACIÓN SECUNDARIA,https://admision.unmsm.edu.pe/Website20262/A/0...

In [31]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_edsecundaria.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: EDUCACIÓN SECUNDARIA
Vacantes obtenidas: 76
Puntaje máximo: 1371.375
Puntaje mínimo: 970.0

    codigo                       apellidos_nombres   puntaje  merito_ep
0   752097                 Alva Alba, Nain Gabriel  1371.375        1.0
1   715969      Valverde Gonzales, Gabriela Medali  1274.875        2.0
2   741473       Coronado Comitivos, Alvaro Leonel  1252.625        3.0
3   734211       Tejada Avellaneda, Darien Antoine  1215.500        4.0
4   777200  Ccotohuanca Patricio, José Luis Arturo  1213.125        5.0
..     ...                                     ...       ...        ...
71  735738       Tapullima Mendez, Daniela Anelins   977.750       72.0
72  750960                 Santiago Flores, Geremi   975.125       73.0
73  820996               Ballon Layme, Victor Hugo   974.875       74.0
74  703652          Arbildo Espino, Stefano Santos   970.000       76.0
75  690249              Llempen Auqui, Jean Carlos   970.000       75.0

[76 rows x 4 columns]

In [32]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/142/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_estadistica.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/142/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 65 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_estadistica.csv
   65 filas  ×  8 columnas

── Observaciones ──
observacion
ALCANZÓ VACANTE          63
INHABILITADO (Art. 5)     2

── Estadísticas de puntaje ──
count      65.000
mean      839.877
std       188.950
min       396.750
25%       713.000
50%       851.250
75%       931.125
max      1446.750

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,212770,"Aguilar Mogollon, Yerson Aarón",ESTADÍSTICA,798.000,43.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
1,211868,"Alomia Fernandez, Jose Luis Jr.",ESTADÍSTICA,927.750,19.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
2,215963,"Aniceto Mamani, Jefferson Aaron",ESTADÍSTICA,564.500,61.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
3,215255,"Arias Sapa, Augusto Andre",ESTADÍSTICA,911.750,21.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
4,215990,"Arteaga Machuca, Hugo Lucio",ESTADÍSTICA,830.625,36.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
5,214027,"Ascue Rondon, Claudia Alexandra",ESTADÍSTICA,396.750,65.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
6,218236,"Basurto Chavez, Ana Karina",ESTADÍSTICA,877.375,30.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
7,216685,"Bernardo Jurado, Piero Teo",ESTADÍSTICA,931.125,17.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
8,214047,"Cabrera Ore, Angello Vincent",ESTADÍSTICA,660.625,55.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
9,216703,"Chua Sayaverde, Valeria Amelia",ESTADÍSTICA,894.375,26.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
10,216139,"Cisneros Ramos, Gustavo",ESTADÍSTICA,748.125,47.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
11,212585,"Cruzado Canchari, Maykel William Del Piero",ESTADÍSTICA,851.250,33.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
12,215404,"Espino Machado, Rodrigo Sebastián",ESTADÍSTICA,987.875,9.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
13,214204,"Fernandez Minaya, Sebastian Giovani",ESTADÍSTICA,986.125,10.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...
14,216484,"Garrido Requelme, Deyvis Yosephi",ESTADÍSTICA,682.500,53.0,ALCANZÓ VACANTE,ESTADÍSTICA,https://admision.unmsm.edu.pe/Website20262/A/1...

In [33]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_estadistica.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: ESTADÍSTICA
Vacantes obtenidas: 63
Puntaje máximo: 1446.75
Puntaje mínimo: 396.75

    codigo                       apellidos_nombres   puntaje  merito_ep
0   218653             Guevara Peña, Alexis Adrian  1446.750        1.0
1   215827                 Ramos Huacho, Aleli Ana  1314.250        2.0
2   213449         Leon Alanoca, Valentina Guisell  1210.375        3.0
3   218256     Gonzales Palacios, Juan José Manuel  1209.125        4.0
4   212836             Quincho Esteban, Mark Blary  1066.500        5.0
..     ...                                     ...       ...        ...
58  215963         Aniceto Mamani, Jefferson Aaron   564.500       61.0
59  211715        Landeo Clerque, Thiago Alejandro   554.750       62.0
60  210737  Maguiña Huachara, Alexsander Guisseppe   516.625       63.0
61  211896            Soto Ipanaqué, Anderson Iván   502.875       64.0
62  214027         Ascue Rondon, Claudia Alexandra   396.750       65.0

[63 rows x 4 columns]

In [1]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/204/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_ia.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/204/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 512 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_ia.csv
   512 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          457
ALCANZÓ VACANTE           44
AUSENTE                    6
INHABILITADO (Art. 5)      5

── Estadísticas de puntaje ──
count     506.000
mean      879.454
std       179.613
min       345.000
25%       743.406
50%       878.688
75%      1006.500
max      1465.000

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,373848,"Abanto Ccahuana, Nicole Alexandra",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,831.000,NaN,SIN OBSERVACIÓN,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
1,341380,"Abanto Ramirez, Abraham Leonardo",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,969.875,NaN,SIN OBSERVACIÓN,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
2,383633,"Accate Marallano, Steven Alonso",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,965.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
3,382198,"Achulli Rivera, Kiara Camila",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,1284.000,7.0,ALCANZÓ VACANTE,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
4,354738,"Aguayo Damacen, Jhoan Galois",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,1030.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
5,358935,"Aguirre Huaringa, Jhoseph Xavier",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,1201.125,21.0,ALCANZÓ VACANTE,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
6,313580,"Albornoz Ortiz, Keyla",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,588.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
7,344268,"Alcantara Melgarejo, Erick",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,839.250,NaN,SIN OBSERVACIÓN,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
8,387067,"Alcántara Murga, Diego Jhair",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,1016.250,NaN,SIN OBSERVACIÓN,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
9,326441,"Alcarraz Gonzales, Luis Miguel",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,902.625,NaN,INHABILITADO (Art. 5),INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
10,393020,"Alcoser Ponce, Sebastian Paolo",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,616.000,NaN,SIN OBSERVACIÓN,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
11,372886,"Aldaba Flores, Andy Joaquin",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,653.125,NaN,SIN OBSERVACIÓN,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
12,342647,"Aldoradin Chirinos, Matias Teobaldo",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,775.125,NaN,SIN OBSERVACIÓN,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
13,358938,"Alhuay Huaman, Jhon Valentin",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,1072.750,NaN,SIN OBSERVACIÓN,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...
14,359499,"Alva Bravo, Ivan Yande",INGENIERÍA DE INTELIGENCIA ARTIFICIAL,934.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE INTELIGENCIA ARTIFICIAL,https://admision.unmsm.edu.pe/Website20262/A/2...

In [2]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_ia.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: INGENIERÍA DE INTELIGENCIA ARTIFICIAL
Vacantes obtenidas: 44
Puntaje máximo: 1465.0
Puntaje mínimo: 1131.0

    codigo                          apellidos_nombres   puntaje  merito_ep
0   388113               Inga Cancho, Dilan Sebastian  1465.000        1.0
1   367558                Castro Neri, David Santiago  1359.375        2.0
2   344878          Collantes Atalaya, Gino Sebastian  1339.375        3.0
3   319780                Melo Ramos, Patrick Jusephy  1305.125        4.0
4   387956          Cardenas Palma, Santiago De Jesus  1301.000        5.0
5   393599              Lopez Bonifacio, Danny Junior  1292.000        6.0
6   382198               Achulli Rivera, Kiara Camila  1284.000        7.0
7   354627            Huaman Chapoñan, Cristian Bryan  1277.125        8.0
8   317298           Morales Alejandro, Anderson Jose  1273.750        9.0
9   354047              Avila Becerra, Arturo Rodrigo  1269.750       10.0
10  385086              Méndez Rosales, Joel Emmanuel  1244.625       11.0
11  332401                 Araujo Razo, Miguel Adrian  1243.875       12.0
12  318497          Pasapera Grabiel, Jeanpol Antonio  1232.625       13.0
13  360119               Fura Almanza, Yosue Humberto  1231.500       14.0
14  353169  Walde Nureña, Gabriel Sebastián Francisco  1224.625       15.0
15  359460           Chirinos Revilla, Cristian Robin  1223.500       16.0
16  366872      Cachay Mesares, Jose Francisco Alonso  1217.750       17.0
17  357417                Blas Ramos, Leonardo Javier  1215.500       18.0
18  378692             Garcia Fernandez, Andres Edwin  1213.750       19.0
19  338352                 Huerta Jara, Lesly Yulissa  1203.500       20.0
20  358935           Aguirre Huaringa, Jhoseph Xavier  1201.125       21.0
21  366072                   Lay Reyes, Fabian Danilo  1197.250       22.0
22  332098                   Tello Garay, Edison Alex  1189.250       23.0
23  340630        Astoquillca Llancul, Jair Janfranco  1185.250       24.0
24  335835                 Trejo Garay, Andrea Ericka  1184.375       25.0
25  336089               Huamani Hancco, Diego Alonso  1182.375       26.0
26  333019                   Poma Cupe, Cristhian Noe  1168.625       27.0
27  389447             Diaz Alvarado, Danaly Jaquelin  1165.250       29.0
28  369303                Ramos Condori, Jose Alberto  1165.250       28.0
29  390779                     Quispe Roca, Sebastian  1164.125       30.0
30  394080                  Vera Sanchez, Dylan Piero  1164.125       31.0
31  374774              Lopez Borja, Javier Alejandro  1160.125       32.0
32  343975                 Soto Bardales, Megan Layne  1156.125       33.0
33  366292           Buhytron Tataje, Angelo Fernando  1152.000       34.0
34  328720         Huaynate Espinoza, Piero Alejandro  1148.125       35.0
35  387268            Naupay Serrano, Joaquin Antonio  1147.000       37.0
36  350855               Montoya Tello, Juan Salvador  1147.000       36.0
37  396396                  Solano Rojas, Loris David  1145.500       38.0
38  353136                De Paz Huerta, Arnold Amiel  1143.500       39.0
39  389152                    Huincho Huamaní, Lucero  1136.000       40.0
40  356319            Arzapalo Arzapalo, Daniel Jesus  1133.875       41.0
41  344343           Valenzuela Pareja, Octavio Dante  1133.250       42.0
42  313973               Carlos Crisanto, Gian Franco  1131.375       43.0
43  340769              Zapana Yucra, Kiara Geraldine  1131.000       44.0

In [3]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/167/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_civil.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/167/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 642 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_civil.csv
   642 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          587
ALCANZÓ VACANTE           37
INHABILITADO (Art. 5)     10
AUSENTE                    8

── Estadísticas de puntaje ──
count     634.000
mean      910.017
std       215.777
min       412.125
25%       750.656
50%       895.188
75%      1051.750
max      1521.500

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,347086,"Abarca Castillo, Fabian Yony",INGENIERÍA CIVIL,1350.250,17.0,ALCANZÓ VACANTE,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
1,317687,"Abollaneda Mamani, Patrick Yhojan",INGENIERÍA CIVIL,1254.875,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
2,373379,"Acevedo Herrera, Meilhyn Claris",INGENIERÍA CIVIL,1122.375,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
3,310073,"Acha Rojas, Joan Francisco",INGENIERÍA CIVIL,852.125,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
4,376815,"Acosta Quesnay, Michael Del Piero",INGENIERÍA CIVIL,1007.625,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
5,372965,"Acuña Becerra, Piero Alessandro",INGENIERÍA CIVIL,737.625,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
6,325491,"Acuña Mallqui, Max Gabriel",INGENIERÍA CIVIL,775.875,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
7,356205,"Aguilar Mejia, Jose Julian",INGENIERÍA CIVIL,864.375,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
8,353553,"Aguilar Morocho, Sebastian Joseph",INGENIERÍA CIVIL,573.875,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
9,326780,"Alanya Tito, Ever Anthony",INGENIERÍA CIVIL,624.000,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
10,319045,"Alaya Saman, Jheison Efrain",INGENIERÍA CIVIL,488.625,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
11,340114,"Alca Olvia, Anghelina Brighid",INGENIERÍA CIVIL,775.875,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
12,358391,"Alcántara Yurivilca, Gian Franco",INGENIERÍA CIVIL,931.750,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
13,380871,"Alcedo Pacheco, Jose Miguel",INGENIERÍA CIVIL,895.750,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...
14,341892,"Alfaro Cabezas, Cristhiam Adrian Jhared",INGENIERÍA CIVIL,1104.750,NaN,SIN OBSERVACIÓN,INGENIERÍA CIVIL,https://admision.unmsm.edu.pe/Website20262/A/1...

In [4]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_civil.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: INGENIERÍA CIVIL
Vacantes obtenidas: 37
Puntaje máximo: 1521.5
Puntaje mínimo: 1269.75

    codigo                       apellidos_nombres   puntaje  merito_ep
0   329798       Pumahuallca Horna, Miguel Mathías  1521.500        1.0
1   365995          Sanchez Uscamayta, Axel Vagner  1471.750        2.0
2   379870               Carlos Suarez, Jean Piere  1465.000        3.0
3   351380           Quispe Velasquez, Luis Delfin  1465.000        4.0
4   334524            Casiano Wilson, Moises Jesus  1440.750        5.0
5   323088           Burgos Vidarte, José Fernando  1430.750        6.0
6   344335           Sanchez Vasquez, Jhimy Harold  1422.750        7.0
7   351750               Tullume Belen, Max Arthur  1421.625        8.0
8   394259            Alfaro Quispe, Fernando José  1418.750        9.0
9   348497             Ayvar Nazario, Matias Aaron  1400.500       10.0
10  350823             Pua Campos, Gonzalo Everton  1399.750       11.0
11  342434  Salvatierra Rivera, Benjamin Gianpiero  1388.375       12.0
12  362381          Garcia Cipriano, Jose Fernando  1367.375       13.0
13  325785           Franco Rojas, Flavio Enmanuel  1365.000       14.0
14  377584         Rosas Rosales, Sebastian Alonso  1356.500       15.0
15  311348              Enciso Perez, Antony Jesus  1352.500       16.0
16  347086            Abarca Castillo, Fabian Yony  1350.250       17.0
17  354207         De La Cruz Ramos, Martin Israel  1344.500       18.0
18  385187           Arias Escudero, Carlos Hernan  1342.250       19.0
19  312965           Vicuña Rivera, Andony Adriano  1341.625       20.0
20  378343            Gaytan Chavez, Hayder Russel  1337.125       21.0
21  340510       Huamani Montalvo, Mathause Camilo  1335.375       22.0
22  398805       Choquecahua Ataucusi, Brayan Raul  1334.250       23.0
23  399417           Muñoz Villegas, Romina Olivia  1333.375       24.0
24  310450           Mendoza Toscano, Robert Piero  1318.250       25.0
25  367169            Hernandez Yauri, Jesús Elías  1314.250       26.0
26  318226                Cabana Ortiz, Jairo Eliy  1290.875       27.0
27  377812      Contreras Arias, Gabriel Sebastián  1282.875       28.0
28  320629         Chaupis Estrada, Samael Michael  1278.875       30.0
29  320275         Canchumanta Montes, Jelsin Abel  1278.875       31.0
30  348663           Mendoza Modesto, Felix Junior  1278.875       29.0
31  380807              Guillen Salazar, Sebastian  1278.875       32.0
32  330608             Rodríguez Díaz, Piero André  1274.875       33.0
33  314545           Cuzcano Amaya, Luis Alejandro  1272.000       34.0
34  334051               Caja Teran, Nataly Ariana  1271.375       35.0
35  342187               Calle Peña, Anderson Juan  1269.750       37.0
36  385539           Yaranga Gutierrez, Saúl David  1269.750       36.0

In [5]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/173/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_seguridad.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/173/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 79 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_seguridad.csv
   79 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          48
ALCANZÓ VACANTE          30
INHABILITADO (Art. 5)     1

── Estadísticas de puntaje ──
count      79.000
mean      860.239
std       154.170
min       521.250
25%       752.375
50%       846.375
75%       956.000
max      1252.625

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,334555,"Achic Vasquez, Estrella Yamil",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,970.000,18.0,ALCANZÓ VACANTE,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
1,384607,"Achulli Truevas, Judith Yomali",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,835.250,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
2,382872,"Aguirre Navarro, Jordan",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,1071.625,7.0,ALCANZÓ VACANTE,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
3,383383,"Aguirre Rodriguez, Caleb Jonas",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,897.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
4,344800,"Alabrin Soto, Vanessa Aracely",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,660.000,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
5,361628,"Alegría Quispe, Isis Alessandra",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,823.250,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
6,340347,"Alvaro Espinoza, Karen Milagros",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,759.000,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
7,395255,"Arias Guzman, Sebastian Daniel",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,766.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
8,323004,"Barja Palma, Cristopher",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,707.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
9,315790,"Caceres Gonzales, Liumbert David",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,684.000,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
10,360041,"Capellino Godoy, Aaron Eduardo",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,1058.500,9.0,ALCANZÓ VACANTE,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
11,348667,"Casafranca Godo, Luis Valentino",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,931.750,24.0,ALCANZÓ VACANTE,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
12,343966,"Cerron Huayhua, Antonella",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,1023.500,14.0,ALCANZÓ VACANTE,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
13,356723,"Chia Rivera, Mario Hiroki",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,944.125,21.0,ALCANZÓ VACANTE,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...
14,319112,"Chullo Ccahua, Reynold Farit",INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,691.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO,https://admision.unmsm.edu.pe/Website20262/A/1...

In [6]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_seguridad.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: INGENIERÍA DE SEGURIDAD Y SALUD EN EL TRABAJO
Vacantes obtenidas: 30
Puntaje máximo: 1252.625
Puntaje mínimo: 902.625

    codigo                   apellidos_nombres   puntaje  merito_ep
0   335150  Gonzales Paucar, Sebastian Nícolas  1252.625        1.0
1   397068          Laurente Aviles, Jhon Wily  1228.625        2.0
2   379484     Dextre Juarez, Adrian Francesco  1143.500        3.0
3   312273     Velasquez Apaza, Cristian Piero  1142.750        4.0
4   352381       Moreno Cahuaza, Andher Gadhit  1123.500        5.0
5   377385     Lopez Chuchon, Betzabeth Selena  1084.125        6.0
6   382872             Aguirre Navarro, Jordan  1071.625        7.0
7   365176      Montes Barrientos, Jesus Simon  1062.500        8.0
8   360041      Capellino Godoy, Aaron Eduardo  1058.500        9.0
9   368968     Talledo Garcia, Rodrigo Nicolas  1048.125       10.0
10  331936        Mendoza Ore, Rocio De Fatima  1042.500       11.0
11  340683       Piscoya Suarez, Maria Manuela  1037.375       12.0
12  371793      Lopez Falcon, Victor Alejandro  1029.375       13.0
13  343966           Cerron Huayhua, Antonella  1023.500       14.0
14  397794       Dolores Albino, Axel Emmanuel  1002.500       15.0
15  323750       Padilla Vargas, Kevin Jhoseph   996.500       16.0
16  398997  Santa Cruz Morales, Hernan Antonio   992.125       17.0
17  334555       Achic Vasquez, Estrella Yamil   970.000       18.0
18  353933    Hipolito Chumbes, Jherson Ronald   956.875       19.0
19  316842       Echevarria Cruz, Jose Antonio   955.125       20.0
20  356723           Chia Rivera, Mario Hiroki   944.125       21.0
21  347492       Escudero Palma, Yamil Alberto   939.750       22.0
22  394623        Ñahuis Guillen, Josue Emilio   932.875       23.0
23  348667     Casafranca Godo, Luis Valentino   931.750       24.0
24  316865     Herrera Rivera, Ricardo Antonio   915.375       25.0
25  363443      Huaman Cangana, Aracely Camila   914.625       26.0
26  355424        Mozo Acuña, Maravilla Romina   914.625       27.0
27  341478             Diaz Ramos, Illary Mary   911.750       28.0
28  341822        Cordova Ravines, Deyvid Joel   905.500       29.0
29  337210        Paredes Meza, Vianca Alondra   902.625       30.0

In [7]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/201/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_sistemas.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/201/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 875 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_sistemas.csv
   875 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          805
ALCANZÓ VACANTE           50
AUSENTE                   13
INHABILITADO (Art. 5)      7

── Estadísticas de puntaje ──
count     862.000
mean      878.758
std       225.099
min       254.750
25%       712.375
50%       858.250
75%      1020.250
max      1557.500

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,367338,"Abanto Ramos, D'Alessandro",INGENIERÍA DE SISTEMAS,789.000,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
1,350381,"Acero Quiñonez, Frank Deyvis",INGENIERÍA DE SISTEMAS,907.750,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
2,374178,"Acevedo Llallahui, Jack Arlington",INGENIERÍA DE SISTEMAS,NaN,NaN,AUSENTE,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
3,388366,"Acosta Gordillo, David Rafael",INGENIERÍA DE SISTEMAS,855.125,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
4,323230,"Acosta Rocca, Deyvis Nicolas",INGENIERÍA DE SISTEMAS,742.750,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
5,334937,"Acosta Vilca, Fatima Valeria",INGENIERÍA DE SISTEMAS,711.875,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
6,395453,"Adrianzén Ramos, Ibrahim Mathias Marto",INGENIERÍA DE SISTEMAS,1017.250,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
7,333169,"Aguilar Briones, Diego Omar",INGENIERÍA DE SISTEMAS,1009.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
8,344640,"Aguirre Arias, Jesus Arnaldo",INGENIERÍA DE SISTEMAS,798.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
9,312329,"Aguirre Macedo, Dante Leonidas",INGENIERÍA DE SISTEMAS,733.625,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
10,333957,"Alanya Ataucusi, Estefany Paola",INGENIERÍA DE SISTEMAS,885.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
11,319039,"Alarcon Cruz, Sebastian Giovanni",INGENIERÍA DE SISTEMAS,523.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
12,387724,"Alarcon Fernandez, Josue Jair",INGENIERÍA DE SISTEMAS,768.250,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
13,390507,"Alarcon Hurtado, Cristhofer Emanuel",INGENIERÍA DE SISTEMAS,657.125,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...
14,310612,"Alarcon Ramos, Fabricio Gerardo",INGENIERÍA DE SISTEMAS,919.625,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SISTEMAS,https://admision.unmsm.edu.pe/Website20262/A/2...

In [8]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_sistemas.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: INGENIERÍA DE SISTEMAS
Vacantes obtenidas: 50
Puntaje máximo: 1557.5
Puntaje mínimo: 1268.0

    codigo                       apellidos_nombres   puntaje  merito_ep
0   316398             Castro Suclupe, Kevin David  1557.500        1.0
1   323395                 Garcia Rubio, Jose Luis  1515.250        2.0
2   318077           Serna Villon, Nincoll Oswaldo  1503.250        3.0
3   337010        Magallanes Cordova, Luis Alberto  1502.125        4.0
4   384547           Roque Tuñoque, Stefany Eylith  1478.125        5.0
5   338350          Coaquira Orihuela, Dayana Ruth  1472.375        6.0
6   326867        Ortiz Mendiburu, Mathias Gabriel  1466.625        7.0
7   377862            Arque Vasquez, Jose Estefano  1451.750        8.0
8   360589           Ramirez Ramos, Juan Alejandro  1446.750        9.0
9   312117             Calderón Rojas, Saih Ramiro  1434.750       10.0
10  343789             Panaifo Quispe, Merli Yugui  1421.625       11.0
11  389976   Huaccaicachacc Bermudo, Aldair Wilber  1418.625       12.0
12  360305            Montero Salazar, Walter Jose  1417.625       13.0
13  319547         Rojas Espinoza, Alexandro David  1417.625       14.0
14  331303          Janampa Bautista, Edgar Daniel  1416.250       15.0
15  372142        Paico Iparraguirre, Cesar Imanol  1413.625       16.0
16  350150          Espinoza Doroteo, Luis Gerardo  1406.125       17.0
17  318911            Villa Sune, Arnold Guillermo  1396.500       18.0
18  384917         Rosales Achic, Daniel Alexander  1374.000       19.0
19  365397             Larico Caqui, Dylan Fabiano  1365.000       20.0
20  311446        Dominguez Guevara, Jhon Williams  1358.250       21.0
21  384650           Herrera Livia, Alejandro Rene  1349.000       22.0
22  365913           Ramirez Jorge, Elvis Benjamin  1348.875       23.0
23  337249                  Rocca Vilca, Jeancarlo  1346.750       24.0
24  382513  De La Cruz Escalante, Christopher Jair  1341.125       25.0
25  344082         Garamendi Bernabel, Jean Pierre  1338.000       26.0
26  372947          Sanchez Gallosa, Steven Gerard  1337.125       27.0
27  346899           Valverde Alberco, Diego Oscar  1334.250       28.0
28  381424       Cuellar Huaynate, Nataly Dayanara  1333.625       29.0
29  364348         Vasquez Rodriguez, Piero Rafael  1327.375       30.0
30  335546                   Retis Rojas, Cristian  1320.500       31.0
31  323690            García Avendaño, Samir Dylan  1318.750       32.0
32  324864            Ramos Huancas, Yors Anderson  1312.000       33.0
33  362040       Guardia Saavedra, Jheison Eduardo  1309.125       34.0
34  360884      Rodriguez Becerra, Guillermo David  1308.000       35.0
35  390818        Gamboa Almeyda, Kiel Ashbel Andy  1308.000       36.0
36  341971            Castro Jauregui, Dario Samir  1302.250       37.0
37  338878          Alcantara Ponce, Daymer Antony  1298.875       39.0
38  335508         Salazar Huaman, Danylo Anderson  1298.875       38.0
39  372652         Castellanos Rivera, Luis Andres  1298.625       40.0
40  339192              Ruiz Alarcon, Lenin Carlos  1294.875       41.0
41  386320        Alhuay Mottoccanche, Italo Edson  1293.125       42.0
42  338055          Salas Cerna, Gustavo Alexander  1290.875       44.0
43  342160             Ramirez Celis, Diego Daniel  1290.875       43.0
44  373987              Vega Valdivia, Luis Alonso  1290.625       45.0
45  372297          Martinez Barrientos, Jose Luis  1290.125       46.0
46  338889             Cahuana Quiquia, Mark Stive  1288.375       47.0
47  353768           Torpoco Cortez, Marco Antonio  1286.750       48.0
48  343372    Rodriguez Pereyra, Luciana Valentina  1273.750       49.0
49  312419           Romero Vicente, Antonio Adiel  1268.000       50.0

In [9]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/193/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_teleco.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/193/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 125 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_teleco.csv
   125 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN    81
ALCANZÓ VACANTE    44

── Estadísticas de puntaje ──
count     125.000
mean      946.820
std       186.999
min       510.375
25%       826.125
50%       956.750
75%      1062.500
max      1410.750

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,377549,"Abanto Torres, Renato Fadull",INGENIERÍA DE TELECOMUNICACIONES,1115.500,22.0,ALCANZÓ VACANTE,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
1,338068,"Adan Cabia, Frank David",INGENIERÍA DE TELECOMUNICACIONES,766.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
2,360385,"Agama Quiliche, Fernando William",INGENIERÍA DE TELECOMUNICACIONES,644.000,NaN,SIN OBSERVACIÓN,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
3,394785,"Alarcon Espinoza, Stefano Russell",INGENIERÍA DE TELECOMUNICACIONES,1053.750,36.0,ALCANZÓ VACANTE,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
4,386070,"Alcantara Meza, Armando Josue",INGENIERÍA DE TELECOMUNICACIONES,1047.875,38.0,ALCANZÓ VACANTE,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
5,383884,"Allccahuaman Llampi, Daniel Anthony",INGENIERÍA DE TELECOMUNICACIONES,914.625,NaN,SIN OBSERVACIÓN,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
6,343350,"Alviz Lopez, Jair Alonso",INGENIERÍA DE TELECOMUNICACIONES,966.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
7,339424,"Alzamora Quiñones, Alejandro Isaias",INGENIERÍA DE TELECOMUNICACIONES,1084.750,28.0,ALCANZÓ VACANTE,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
8,343691,"Amambal Huaman, Diego Madinson",INGENIERÍA DE TELECOMUNICACIONES,1213.125,10.0,ALCANZÓ VACANTE,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
9,375415,"Anaya Venegas, Anderson Neysser",INGENIERÍA DE TELECOMUNICACIONES,1410.750,1.0,ALCANZÓ VACANTE,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
10,357580,"Antonio Ruiz, Erick Daniel",INGENIERÍA DE TELECOMUNICACIONES,1016.250,NaN,SIN OBSERVACIÓN,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
11,344991,"Antunez Ysturiz, Wilder Daniel",INGENIERÍA DE TELECOMUNICACIONES,1300.500,4.0,ALCANZÓ VACANTE,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
12,339674,"Arapa Pino, Diego Renzo",INGENIERÍA DE TELECOMUNICACIONES,861.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
13,348664,"Arevalo Garcia, Alexander Marcelo",INGENIERÍA DE TELECOMUNICACIONES,1131.500,19.0,ALCANZÓ VACANTE,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...
14,319799,"Asencios Alvarez, Jheremy Lennin",INGENIERÍA DE TELECOMUNICACIONES,1192.000,14.0,ALCANZÓ VACANTE,INGENIERÍA DE TELECOMUNICACIONES,https://admision.unmsm.edu.pe/Website20262/A/1...

In [10]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_teleco.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: INGENIERÍA DE TELECOMUNICACIONES
Vacantes obtenidas: 44
Puntaje máximo: 1410.75
Puntaje mínimo: 1025.375

    codigo                      apellidos_nombres   puntaje  merito_ep
0   375415        Anaya Venegas, Anderson Neysser  1410.750        1.0
1   373241  Torres Bautista, Eder Juan Sebasthian  1351.375        2.0
2   390407     Zuñiga Macchiavello, Mateo Rodrigo  1331.375        3.0
3   344991         Antunez Ysturiz, Wilder Daniel  1300.500        4.0
4   376032      Gutierrez Isidro, Fernando Alonso  1290.875        5.0
5   398659        Estrada Zuasnabar, Jose Rodolfo  1282.875        6.0
6   358204             Roca Ccacca, William Oscar  1252.625        7.0
7   346072          Cahuana Canaza, Aziel Mathieu  1249.750        8.0
8   310373        Quiñonez Mozo, Brayan Sebastian  1238.875        9.0
9   343691         Amambal Huaman, Diego Madinson  1213.125       10.0
10  381304       López Hidalgo, Sebastian Alberto  1207.500       11.0
11  390716             Benites Mota, Clisman Hugo  1204.000       12.0
12  341820        Nuñez Gonzales, Julio Alexander  1194.375       13.0
13  319799       Asencios Alvarez, Jheremy Lennin  1192.000       14.0
14  333561         Cahuapaza Ramos, Anguello Ivan  1179.875       15.0
15  358731       Mallma Barreda, Matías Alejandro  1168.125       16.0
16  370932              Rivera Reyes, David Piero  1164.125       17.0
17  318521            Cerdán García, Carlos Ruben  1136.125       18.0
18  348664      Arevalo Garcia, Alexander Marcelo  1131.500       19.0
19  339146         Portugal De La Cruz, Alex Jair  1117.875       20.0
20  394052        Leon Yaipen, Alesandro Fernando  1117.500       21.0
21  355483                Zea Sosa, Yeandel Pedro  1115.500       23.0
22  377549           Abanto Torres, Renato Fadull  1115.500       22.0
23  355594        Reyes Fernandez, Johan Anderson  1100.750       24.0
24  339909                Ramos Leon, Bryhan Abel  1100.750       25.0
25  336552           Salas Allauca, Jeremy Nilmar  1097.500       26.0
26  376777       De La Cruz Ramirez, Darin Fabian  1087.625       27.0
27  339424    Alzamora Quiñones, Alejandro Isaias  1084.750       28.0
28  351796        Sanchez Quispe, Franco Vladimir  1084.750       29.0
29  329257                Liza Chui, Alonso Mateo  1083.625       30.0
30  344674      Terrazas Palomino, Sebastian Aron  1067.625       31.0
31  357921                 Oscco Pongo, Aldo Ivan  1062.500       32.0
32  397681             Hidalgo Alvis, Rafael Jehu  1061.875       33.0
33  336215                  Nakamatsu Cruz, Akemi  1058.500       34.0
34  345761         Guadalupe Pelaez, Rodrigo Juan  1056.750       35.0
35  394785      Alarcon Espinoza, Stefano Russell  1053.750       36.0
36  342455                 Sosa Silva, Edú Rafael  1049.375       37.0
37  386070          Alcantara Meza, Armando Josue  1047.875       38.0
38  372081          Mallma Bautista, Iñigo Hector  1047.500       39.0
39  380909            Martinez Calcina, Andy Luis  1041.875       40.0
40  379985           Pardo Alvarado, Luz Princesa  1040.750       41.0
41  373522             Quenta Huamani, Saul Johan  1035.000       42.0
42  372275                Zamora Baca, Giancarlos  1029.375       43.0
43  315350          Guevara Yubau, Eliseo Gabriel  1025.375       44.0

In [11]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/175/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_transportes.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/175/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 172 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_transportes.csv
   172 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN    128
ALCANZÓ VACANTE     44

── Estadísticas de puntaje ──
count     172.000
mean      815.821
std       162.479
min       449.250
25%       703.562
50%       812.625
75%       913.094
max      1275.375

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,329025,"Abanto Mendoza, Laura Anais",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,930.875,40.0,ALCANZÓ VACANTE,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
1,325948,"Aguilar Villagomez, Edgar Junior",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,1025.250,19.0,ALCANZÓ VACANTE,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
2,393058,"Aguirre Perfecto, Samuel Elias",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,965.250,33.0,ALCANZÓ VACANTE,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
3,343172,"Alminagorda Flores, Noe Eleazar",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,893.500,NaN,SIN OBSERVACIÓN,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
4,317707,"Altamirano Julca, Jefferson",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,885.500,NaN,SIN OBSERVACIÓN,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
5,374327,"Alvarado Cabrera, Piero Valentin",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,1063.625,11.0,ALCANZÓ VACANTE,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
6,352212,"Alvarado Galarza, Katherine Silvia",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,779.875,NaN,SIN OBSERVACIÓN,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
7,360325,"Alvarado Huayllani, Oscar Andre",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,839.250,NaN,SIN OBSERVACIÓN,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
8,333766,"Alvarez Sifuentes, Jesus Cluber",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,616.750,NaN,SIN OBSERVACIÓN,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
9,382875,"Alvarez Taipe, Jhon Linder",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,813.000,NaN,SIN OBSERVACIÓN,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
10,375066,"Alvaro Pachas, Diego Alberto",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,934.000,39.0,ALCANZÓ VACANTE,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
11,367997,"Anchiraico Ayala, Dayana Belen",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,946.875,36.0,ALCANZÓ VACANTE,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
12,324266,"Andrade Garcia, Mathias Andre",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,601.000,NaN,SIN OBSERVACIÓN,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
13,311449,"Angoma Ramos, Danusca Kimee",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,869.500,NaN,SIN OBSERVACIÓN,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...
14,392060,"Apaza Apaza, Angelina Nicole",INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,731.875,NaN,SIN OBSERVACIÓN,INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS,https://admision.unmsm.edu.pe/Website20262/A/1...

In [12]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_transportes.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: INGENIERIA DE TRANSPORTES Y SISTEMAS FERROVIARIOS
Vacantes obtenidas: 44
Puntaje máximo: 1275.375
Puntaje mínimo: 912.875

    codigo                        apellidos_nombres   puntaje  merito_ep
0   386014     Barzola Del Carpio, Alessandro Piero  1275.375        1.0
1   381352             Jara Sanchez, Osmar Santiago  1240.625        2.0
2   333619             Chaccha Quispe, Thiago Mateo  1185.250        3.0
3   348194               Perez Quispe, Henry Jostin  1156.125        4.0
4   394476          Armuto Sabrera, Nicole Sthefany  1143.000        5.0
5   350875                     Vasquez Mori, Andres  1125.875        6.0
6   338604          Piscoya Bustamante, Juan Manuel  1088.125        7.0
7   368365            Vicerrel Chávez, José Alberto  1079.625        8.0
8   365432              Pagan Luis, Gonzalo Emanuel  1077.750        9.0
9   376926              Deudor Astete, Alizee Avril  1068.750       10.0
10  374327         Alvarado Cabrera, Piero Valentin  1063.625       11.0
11  339210            Bolaños Vega, Valentino Bryan  1058.500       12.0
12  355064           Calvo Paredes, Santiago Javier  1058.500       13.0
13  364896          Patricio Chacon, Leonardo Terry  1058.500       14.0
14  342969       Torres Barrezueta, Claudio Gabriel  1054.500       15.0
15  368923            Estrada Vega, Cesar Alejandro  1041.250       16.0
16  355530      Apolinario Bardales, Carlos Adriano  1034.375       17.0
17  377289        Rojas Carrasco, Brandon Alexander  1029.875       18.0
18  325948         Aguilar Villagomez, Edgar Junior  1025.250       19.0
19  371682  Cassano Arango, José Alexandre Fauricio  1007.625       20.0
20  393372               Tavara Arcela, Lexa Yamile  1005.625       21.0
21  383793                Cruz Guzman, Matias Jesus  1003.625       22.0
22  331474                    Macha Gamarra, Adolfo  1000.250       23.0
23  387212           Arana Mendoza, Jhianlui Fabian   997.375       24.0
24  339881      Mohenos Medina, Luis Miguel Anthony   995.125       25.0
25  363858            Palma Rivera, Nilton Fabrizio   990.875       26.0
26  384506         Apaza Chocce, Milagros Marianela   987.000       27.0
27  354426             Soto Huaman, Willer Fabricio   986.000       28.0
28  350035              Lopez Valera, Flavio Andres   984.125       29.0
29  380173            Palacios Torres, Adrian David   982.500       30.0
30  373319              Palomino Alejandria, Lisbet   975.125       31.0
31  380064            Chavez Julian, De Carlo David   970.000       32.0
32  393058           Aguirre Perfecto, Samuel Elias   965.250       33.0
33  326854             Naupay Condori, Reimond Joel   960.875       34.0
34  362279      Cruzado Pomalaza, Joaquin Valentino   952.875       35.0
35  367997           Anchiraico Ayala, Dayana Belen   946.875       36.0
36  372184          Sullon Guerra, Ariana Geraldine   944.125       37.0
37  392704       Carranza Rodriguez, Greysi Valeria   935.750       38.0
38  375066             Alvaro Pachas, Diego Alberto   934.000       39.0
39  329025              Abanto Mendoza, Laura Anais   930.875       40.0
40  395014        Reginaldo Guerrero, Kristhel Tais   918.500       41.0
41  316082            Puente Esteban, Jhonny Manuel   918.000       42.0
42  358947              Polo Minaya, Kori Jewellery   913.750       43.0
43  391792           Cardenas Vasquez, Angel Daniel   912.875       44.0

In [13]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/191/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_electronica.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/191/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 255 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_electronica.csv
   255 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          191
ALCANZÓ VACANTE           61
AUSENTE                    2
INHABILITADO (Art. 5)      1

── Estadísticas de puntaje ──
count     253.000
mean      916.825
std       198.629
min       362.000
25%       786.750
50%       911.125
75%      1058.500
max      1407.250

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,359513,"Aburto Bonilla, Josue Marco",INGENIERÍA ELECTRÓNICA,1075.875,56.0,ALCANZÓ VACANTE,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
1,378275,"Agama De La Cruz, Leonel Angel",INGENIERÍA ELECTRÓNICA,1075.625,57.0,ALCANZÓ VACANTE,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
2,344010,"Aguilar Quispe, Yandel Sthee",INGENIERÍA ELECTRÓNICA,1014.625,NaN,SIN OBSERVACIÓN,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
3,345548,"Aguilar Ramirez, Kevin Antony",INGENIERÍA ELECTRÓNICA,1331.750,4.0,ALCANZÓ VACANTE,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
4,373284,"Alarcón Céspedes, Jhanpool Alexander",INGENIERÍA ELECTRÓNICA,826.125,NaN,SIN OBSERVACIÓN,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
5,367668,"Alcantara Delgado, Fabrcio Axel",INGENIERÍA ELECTRÓNICA,942.250,NaN,SIN OBSERVACIÓN,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
6,346253,"Almandos Natividad, Yerimen Brissel",INGENIERÍA ELECTRÓNICA,948.875,NaN,SIN OBSERVACIÓN,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
7,349372,"Alvarado Orellana, Maycol Esteban",INGENIERÍA ELECTRÓNICA,1388.500,2.0,ALCANZÓ VACANTE,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
8,380753,"Alvarez Menendez, Alessa Dasha",INGENIERÍA ELECTRÓNICA,1040.375,NaN,SIN OBSERVACIÓN,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
9,384446,"Alvarez Sandoval, Angel Manuel",INGENIERÍA ELECTRÓNICA,630.875,NaN,SIN OBSERVACIÓN,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
10,362936,"Alvarez Zavala, Raul Alejandro",INGENIERÍA ELECTRÓNICA,1290.875,NaN,INHABILITADO (Art. 5),INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
11,313068,"Alvino Macalopu, Javier Anthony",INGENIERÍA ELECTRÓNICA,1199.375,21.0,ALCANZÓ VACANTE,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
12,359781,"Ancco Aucca, Sebastian Jaki",INGENIERÍA ELECTRÓNICA,961.875,NaN,SIN OBSERVACIÓN,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
13,371722,"Arenas Barrera, Mathias Gastón",INGENIERÍA ELECTRÓNICA,1220.625,19.0,ALCANZÓ VACANTE,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...
14,357699,"Aréstegui Allpaja, Rodrigo Esteban",INGENIERÍA ELECTRÓNICA,794.125,NaN,SIN OBSERVACIÓN,INGENIERÍA ELECTRÓNICA,https://admision.unmsm.edu.pe/Website20262/A/1...

In [14]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_electronica.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: INGENIERÍA ELECTRÓNICA
Vacantes obtenidas: 61
Puntaje máximo: 1407.25
Puntaje mínimo: 1065.875

    codigo                  apellidos_nombres   puntaje  merito_ep
0   363222                Ruiz Paulino, Johan  1407.250        1.0
1   349372  Alvarado Orellana, Maycol Esteban  1388.500        2.0
2   343161         Montes Hoyos, Erick Franco  1343.375        3.0
3   345548      Aguilar Ramirez, Kevin Antony  1331.750        4.0
4   373993     Llacctas Diaz, Esteban Antonio  1298.750        5.0
..     ...                                ...       ...        ...
56  378275     Agama De La Cruz, Leonel Angel  1075.625       57.0
57  313637    Miñano Castillo, Fabian Nicolas  1073.875       58.0
58  342327     Herrera Osorio, Celeste Romina  1073.000       59.0
59  384804    Caqui Chamorro, Keyla Katherine  1066.750       60.0
60  370353              Quispe Flores, Samuel  1065.875       61.0

[61 rows x 4 columns]

In [15]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/171/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_industrial.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/171/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 866 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_industrial.csv
   866 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          759
ALCANZÓ VACANTE           90
AUSENTE                    9
INHABILITADO (Art. 5)      8

── Estadísticas de puntaje ──
count     857.000
mean      894.344
std       214.012
min       404.500
25%       730.750
50%       884.250
75%      1046.500
max      1613.375

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,350005,"Abregu Licla, Rodrigo Alexis",INGENIERÍA INDUSTRIAL,1126.375,NaN,SIN OBSERVACIÓN,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
1,387375,"Abregu Ñahuinripa, Leonel Steffano",INGENIERÍA INDUSTRIAL,978.000,NaN,SIN OBSERVACIÓN,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
2,315675,"Acevedo Nunez, Cielo Nicole",INGENIERÍA INDUSTRIAL,682.250,NaN,SIN OBSERVACIÓN,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
3,354866,"Acosta Querevalu, Estrella Milagros",INGENIERÍA INDUSTRIAL,1012.250,NaN,SIN OBSERVACIÓN,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
4,329811,"Acuña Palacios, Valeria Lizbeth",INGENIERÍA INDUSTRIAL,729.750,NaN,SIN OBSERVACIÓN,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
5,378570,"Adriano Arribasplata, Alvaro Antonio",INGENIERÍA INDUSTRIAL,857.125,NaN,SIN OBSERVACIÓN,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
6,375960,"Aguila Gaspar, Juan Jose",INGENIERÍA INDUSTRIAL,717.625,NaN,SIN OBSERVACIÓN,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
7,389924,"Aguilar Bendita, Pamela",INGENIERÍA INDUSTRIAL,977.000,NaN,SIN OBSERVACIÓN,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
8,390632,"Aguilar Echevarria, Mathías Angel",INGENIERÍA INDUSTRIAL,1343.375,20.0,ALCANZÓ VACANTE,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
9,313318,"Aguilar Perales, Andres",INGENIERÍA INDUSTRIAL,996.250,NaN,SIN OBSERVACIÓN,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
10,349209,"Aguirre Calixto, Pedro Angel Alessandro",INGENIERÍA INDUSTRIAL,531.500,NaN,SIN OBSERVACIÓN,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
11,396189,"Aguirre Palomino, Fred Francesco",INGENIERÍA INDUSTRIAL,866.500,NaN,SIN OBSERVACIÓN,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
12,351357,"Agurto Nizama, Alison Nayeli",INGENIERÍA INDUSTRIAL,683.000,NaN,SIN OBSERVACIÓN,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
13,393360,"Albino Hipolo, Jhilary Yomira",INGENIERÍA INDUSTRIAL,833.750,NaN,SIN OBSERVACIÓN,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...
14,362886,"Albornoz Apaza, Jacob Dennis",INGENIERÍA INDUSTRIAL,1185.250,77.0,ALCANZÓ VACANTE,INGENIERÍA INDUSTRIAL,https://admision.unmsm.edu.pe/Website20262/A/1...

In [16]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_industrial.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: INGENIERÍA INDUSTRIAL
Vacantes obtenidas: 90
Puntaje máximo: 1613.375
Puntaje mínimo: 1164.125

    codigo                   apellidos_nombres   puntaje  merito_ep
0   363732      Bruno Anchaise, Giovanni Paolo  1613.375        1.0
1   359250        Dextre Moran, Maria Fernanda  1506.000        2.0
2   371466        Toribio Jara, Oscar Fernando  1467.875        3.0
3   394949  Alderete Castillo, Fernando Alonso  1467.875        4.0
4   322242      Vasquez Uribe, Alessandro José  1447.875        5.0
..     ...                                 ...       ...        ...
85  389996      Cabezas Aspajo, Luciano Adrien  1168.125       85.0
86  391223    Delgado Custodio, Anny Stephanie  1166.750       87.0
87  339114   Castro Gamarra, Evanjhely Solange  1165.750       88.0
88  355253  Bonifacio Quispe, Camila Alexandra  1165.250       89.0
89  395945    Carhuapoma Achalma, Mario Alonso  1164.125       90.0

[90 rows x 4 columns]

In [17]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/195/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_mecatronica.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/195/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 291 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_mecatronica.csv
   291 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          243
ALCANZÓ VACANTE           35
INHABILITADO (Art. 5)     12
AUSENTE                    1

── Estadísticas de puntaje ──
count     290.000
mean      905.824
std       192.248
min       370.625
25%       752.969
50%       907.750
75%      1036.938
max      1434.750

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,338499,"Abarca Lapa, Deyvid Renzo",INGENIERÍA MECATRONICA,828.125,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
1,344362,"Acero Reyes, Arian Gerard Valentino",INGENIERÍA MECATRONICA,1171.500,24.0,ALCANZÓ VACANTE,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
2,354193,"Acuña Cabrera, Ronal",INGENIERÍA MECATRONICA,1031.625,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
3,321666,"Aguilar Becerra, Santiago Sebastian",INGENIERÍA MECATRONICA,974.000,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
4,340164,"Alarcon Ortiz, Daniel",INGENIERÍA MECATRONICA,1041.375,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
5,363193,"Alatrista Abad, Sonia Paola",INGENIERÍA MECATRONICA,868.375,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
6,324399,"Albites Padilla, Renzo Jairo",INGENIERÍA MECATRONICA,1020.250,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
7,382664,"Alfaro Monge, Kristofer Samir",INGENIERÍA MECATRONICA,948.875,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
8,332479,"Alvino Llanos, Leonardo Miguel",INGENIERÍA MECATRONICA,995.125,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
9,368289,"Angeles Gonzales, Alvaro",INGENIERÍA MECATRONICA,624.000,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
10,328731,"Aranda Quispe, Piero Alexander",INGENIERÍA MECATRONICA,823.250,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
11,376853,"Arango Vasquez, Alvaro Eduardo",INGENIERÍA MECATRONICA,884.125,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
12,360827,"Arbocco Reyes, Santiago Yumi",INGENIERÍA MECATRONICA,751.875,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
13,317270,"Arias Rios, Sebastian Alonso",INGENIERÍA MECATRONICA,1017.500,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...
14,349911,"Arisaca Nina, Said Antony",INGENIERÍA MECATRONICA,799.125,NaN,SIN OBSERVACIÓN,INGENIERÍA MECATRONICA,https://admision.unmsm.edu.pe/Website20262/A/1...

In [18]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_mecatronica.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: INGENIERÍA MECATRONICA
Vacantes obtenidas: 35
Puntaje máximo: 1434.75
Puntaje mínimo: 1125.75

    codigo                    apellidos_nombres   puntaje  merito_ep
0   321159         Machaca Surco, Alvaro Manuel  1434.750        1.0
1   330048            Zamata Rios, Leonard Rene  1399.875        2.0
2   351082           Ortiz Palacio, José Alonso  1396.500        3.0
3   358030       Puertas Olivares, Erick Daniel  1385.625        4.0
4   366451     Millones Velasquez, Josue Miguel  1359.250        5.0
5   393455               Vivanco Ccencho, Angel  1332.500        6.0
6   315338          Baldeon Condori, Matt Calef  1329.125        7.0
7   331404       Quiroz Cabanillas, André Aymar  1307.875        8.0
8   391477     Encarnacion Polo, Harold Patrick  1294.875        9.0
9   348247       Chura Callizana, Aaron Rodrigo  1273.750       10.0
10  357807    Huaman Romani, Roderick Eloy Paul  1256.625       11.0
11  328530        Nieble Espinoza, Jose Gustavo  1252.625       12.0
12  350415      Garcia Maihuire, Alexei Rodrigo  1238.750       13.0
13  317535  Villalobos Huacausi, Ivan Alexander  1227.500       14.0
14  382583            Morales Jamanca, Mauricio  1221.125       15.0
15  328533       Arrambide Reyes, Hayro Anthony  1215.125       16.0
16  330142      Santeliz Ereú, Andrés Alejandro  1197.250       17.0
17  320125       Mendez Ramirez, Sandro Yanpier  1193.250       18.0
18  345086     Pacheco Trinidad, Maycol Estiven  1190.375       19.0
19  398968   De La Calle Rojas, Domenika Romina  1186.375       20.0
20  338447            Calvo Roque, Aaron Misael  1185.250       21.0
21  392378   Vidurizaga Estrada, Dulce Gabriela  1182.375       22.0
22  365413        Rivera Mattos, Andres Eduardo  1174.375       23.0
23  344362  Acero Reyes, Arian Gerard Valentino  1171.500       24.0
24  355965        Peñaran Laines, Fabian Alonso  1168.125       25.0
25  325555  Encinas Tapullima, Andreev Yhonatan  1165.250       26.0
26  372749     Rodríguez Sánchez, Fabio Adriano  1159.875       27.0
27  390567      Vasquez Cardoso, Fabrizio Jesus  1152.625       28.0
28  321992             Callan Paico, Saul Edson  1148.125       29.0
29  368214       Carrizales Sánchez, Kevin José  1139.000       30.0
30  396340          Julca Pachas, Angel Mathias  1138.250       31.0
31  361474      Pacori Garcia, Alejandro Alexis  1135.000       32.0
32  393423  Romero Montes De Oca, Andrea Leonor  1129.875       33.0
33  324141          Campos Cordova, Mar Anthony  1125.875       34.0
34  368510           Mejia Mejia, Angel Gabriel  1125.750       35.0

In [19]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/165/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_minas.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/165/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 275 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_minas.csv
   275 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          240
ALCANZÓ VACANTE           25
AUSENTE                    5
INHABILITADO (Art. 5)      5

── Estadísticas de puntaje ──
count     270.000
mean      852.101
std       206.899
min       230.000
25%       703.844
50%       826.125
75%       996.062
max      1314.250

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,338269,"Acero Infante, Gabriel Adrian",INGENIERÍA DE MINAS,1046.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
1,339663,"Aedo Pillaca, Juan Diego",INGENIERÍA DE MINAS,1139.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
2,338773,"Aguilar Quispe, Marco Antonio",INGENIERÍA DE MINAS,814.125,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
3,384482,"Aguirre Luna, Gerson Marcelo",INGENIERÍA DE MINAS,718.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
4,335921,"Alata Lira, Deivid Alexander",INGENIERÍA DE MINAS,703.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
5,399129,"Aldave Altamirano, Jeyson Fidel",INGENIERÍA DE MINAS,786.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
6,312607,"Alejo Galindo, Yanlui Johan",INGENIERÍA DE MINAS,926.000,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
7,370688,"Amaya Montesinos, Jurgen Gerard",INGENIERÍA DE MINAS,956.875,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
8,386195,"Ambrosio Hermoza, Milagros Elizabeth",INGENIERÍA DE MINAS,673.750,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
9,329909,"Aponte Sanchez, Hana Farah",INGENIERÍA DE MINAS,910.625,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
10,324925,"Aranda Castañeda, Treicy Maryori",INGENIERÍA DE MINAS,748.250,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
11,337009,"Arbaiza Sanchez, Naomi Yennifer",INGENIERÍA DE MINAS,716.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
12,342746,"Arce Castillo, Piero Sebastian",INGENIERÍA DE MINAS,705.000,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
13,366528,"Arce Lliuya, Jordy Roit",INGENIERÍA DE MINAS,1202.375,20.0,ALCANZÓ VACANTE,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...
14,361774,"Argote Ruíz, Celso Daniel Alonzo",INGENIERÍA DE MINAS,728.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE MINAS,https://admision.unmsm.edu.pe/Website20262/A/1...

In [20]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_minas.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: INGENIERÍA DE MINAS
Vacantes obtenidas: 25
Puntaje máximo: 1314.25
Puntaje mínimo: 1175.375

    codigo                         apellidos_nombres   puntaje  merito_ep
0   336488         Contreras Palacios, Josue Nicolas  1314.250        1.0
1   346707      Astocóndor Caldas, Fabrizzio Luciano  1311.875        2.0
2   380013       Quispe Aniceto, Crhistopher Gabriel  1301.000        3.0
3   368883                 Romero Soto, Juan Alfonso  1294.875        4.0
4   325659     Moreno Huamani, Aldo Santiago Joaquín  1280.000        5.0
5   341912                     Rocha Chavez, Jhordan  1273.125        6.0
6   322576          Bazan Cabrera, Christopher Drake  1270.875        7.0
7   324443               Roncal Millan, Diego Anibal  1269.750        8.0
8   365235  Ortiz Mostacero, Jose Cristian Del Piero  1257.125        9.0
9   355689            Garcia Rodriguez, Davis Jostin  1254.875       10.0
10  325079       Rodriguez Chuquihuamani, Grace Mell  1254.000       11.0
11  347054                Centeno Benites, Jose Luis  1244.625       12.0
12  363132                 Pérez Elias, Luis Gabriel  1236.625       13.0
13  352619               Calla Gabriel, Piero Javier  1231.500       14.0
14  362472                 Jaimes Espinoza, Rony Sny  1228.625       15.0
15  334324          Huincho Ramos, Denilson Giovvani  1210.375       16.0
16  369011              Quezada Perez, Smith Esteban  1210.250       17.0
17  387938                  Lopez Guiño, Piero David  1207.500       18.0
18  318713               Vega Camargo, Diego Teofilo  1205.750       19.0
19  366528                   Arce Lliuya, Jordy Roit  1202.375       20.0
20  377639       Crisostomo Egusquiza, Daniel Antony  1194.375       21.0
21  323258               Chipana Apaza, Fiorella Liz  1190.375       22.0
22  367143                    Cabrera Rivera, Franco  1186.375       23.0
23  329673             Ninahuanca Yantas, Axel Bryan  1184.500       24.0
24  352887             Rivera Rosales, Yolita Sahori  1175.375       25.0

In [21]:
import time
import base64
import pandas as pd
from bs4 import BeautifulSoup
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ══════════════════════════════════════════════
# ▶ CONFIGURACIÓN
# ══════════════════════════════════════════════

URL            = "https://admision.unmsm.edu.pe/Website20262/A/202/results.html"
BATCH_RUTAS    = []   # ejemplo: ["A/091", "A/092"]
ARCHIVO_SALIDA = "resultados_unmsm_software.csv"
BASE_URL       = "https://admision.unmsm.edu.pe/Website20262"
WAIT_SEGUNDOS  = 8

# ══════════════════════════════════════════════


def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    )
    return webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=opciones
    )


def mostrar_todas_las_filas(driver):
    """
    Intenta mostrar TODOS los registros de una vez usando 3 estrategias:
    1. Cambiar el select de longitud de DataTables a -1 (All) vía Selenium
    2. Forzarlo por JavaScript directamente sobre la instancia DataTable
    3. Si no hay selector, navegar página por página
    """
    wait = WebDriverWait(driver, 10)

    # ── Estrategia 1: select de longitud (típico en DataTables) ──────────
    try:
        select_el = wait.until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "select[name*='length'], select[name*='DataTables']"))
        )
        select = Select(select_el)
        try:
            select.select_by_value("-1")
            print("  [✓] Paginación: seleccionado 'Todos' en el select.")
        except Exception:
            opciones_vals = [o.get_attribute("value") for o in select.options]
            select.select_by_value(opciones_vals[-1])
            print(f"  [✓] Paginación: seleccionado valor máximo ({opciones_vals[-1]}) en el select.")
        time.sleep(3)
        return "select"
    except Exception:
        pass

    # ── Estrategia 2: forzar via JavaScript DataTables API ───────────────
    try:
        driver.execute_script("""
            var tables = $.fn.dataTable ? $.fn.dataTable.tables() : [];
            if (tables.length > 0) {
                $(tables[0]).DataTable().page.len(-1).draw();
            }
        """)
        time.sleep(3)
        print("  [✓] Paginación: forzado via DataTables JS API.")
        return "js"
    except Exception:
        pass

    # ── Estrategia 3: paginación manual (clic en "Siguiente") ────────────
    print("  [!] Usando paginación manual página por página...")
    return "manual"


def obtener_html_completo(driver, url: str) -> str:
    """Carga la página y retorna el HTML con TODOS los registros visibles."""
    driver.get(url)
    time.sleep(WAIT_SEGUNDOS)

    modo = mostrar_todas_las_filas(driver)

    if modo == "manual":
        return obtener_html_paginado(driver)

    return driver.page_source


def obtener_html_paginado(driver) -> str:
    """
    Recorre todas las páginas haciendo clic en 'Siguiente'
    y acumula los <tr> de cada página en una tabla unificada.
    """
    todas_filas_html = []
    pagina = 1

    while True:
        soup  = BeautifulSoup(driver.page_source, "html.parser")
        tabla = soup.find("table")
        if tabla:
            filas = tabla.find_all("tr")[1:]  # sin encabezado
            todas_filas_html.extend([str(f) for f in filas])
            print(f"    Página {pagina}: {len(filas)} filas | total acumulado: {len(todas_filas_html)}")

        try:
            siguiente = driver.find_element(
                By.CSS_SELECTOR,
                "a.paginate_button.next:not(.disabled), button.paginate_button.next:not(.disabled)"
            )
            siguiente.click()
            pagina += 1
            time.sleep(2)
        except Exception:
            print(f"    Fin de paginación en página {pagina}.")
            break

    # Reconstruir HTML con todas las filas
    soup_base  = BeautifulSoup(driver.page_source, "html.parser")
    tabla_base = soup_base.find("table")
    if tabla_base:
        tbody = tabla_base.find("tbody")
        if tbody:
            tbody.clear()
            for fila_html in todas_filas_html:
                tbody.append(BeautifulSoup(fila_html, "html.parser"))
    return str(soup_base)


def decodificar_b64(valor: str) -> str:
    try:
        return base64.b64decode(valor).decode("utf-8").strip()
    except Exception:
        return valor.strip()


def extraer_carrera(soup: BeautifulSoup) -> str:
    items = soup.select("ol li, ul.breadcrumb li")
    if items:
        return items[-1].get_text(strip=True)
    h1 = soup.find("h1")
    return h1.get_text(strip=True) if h1 else "DESCONOCIDA"


def normalizar_obs(val: str) -> str:
    v = val.strip().upper()
    if "ALCANZ" in v and "VACANTE" in v:
        return "ALCANZÓ VACANTE"
    if "AUSENTE" in v:
        return "AUSENTE"
    if "ART" in v:
        return "INHABILITADO (Art. 5)"
    return v if v else "SIN OBSERVACIÓN"


def parse_tabla(html: str, url: str) -> pd.DataFrame:
    soup  = BeautifulSoup(html, "html.parser")
    tabla = soup.find("table")

    if tabla is None:
        print(f"[AVISO] No se encontró tabla en: {url}")
        return pd.DataFrame()

    filas = []
    for tr in tabla.find_all("tr")[1:]:
        celdas = tr.find_all("td")
        if not celdas:
            continue

        codigo  = celdas[0].get_text(strip=True) if len(celdas) > 0 else ""

        nombre = ""
        if len(celdas) > 1:
            span = celdas[1].find("span", class_="obfuscated")
            nombre = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[1].get_text(strip=True)

        escuela = ""
        if len(celdas) > 2:
            span = celdas[2].find("span", class_="obfuscated")
            escuela = decodificar_b64(span["data-auth"]) if (span and span.get("data-auth")) else celdas[2].get_text(strip=True)

        puntaje = celdas[3].get("data-score", "").strip() if len(celdas) > 3 else ""
        merito  = celdas[4].get("data-merit", "").strip() if len(celdas) > 4 else ""
        obs     = celdas[5].get_text(strip=True)          if len(celdas) > 5 else ""

        filas.append({
            "codigo":            codigo,
            "apellidos_nombres": nombre,
            "escuela":           escuela,
            "puntaje":           puntaje,
            "merito_ep":         merito,
            "observacion":       obs,
        })

    if not filas:
        print(f"[AVISO] Sin filas en: {url}")
        return pd.DataFrame()

    df = pd.DataFrame(filas)
    df["codigo"] = df["codigo"].str.strip()
    df["apellidos_nombres"] = (
        df["apellidos_nombres"].str.strip().str.title()
        .str.replace(r"\s{2,}", " ", regex=True)
    )
    df["puntaje"]    = pd.to_numeric(df["puntaje"],  errors="coerce")
    df["merito_ep"]  = pd.to_numeric(df["merito_ep"], errors="coerce")
    df["observacion"] = df["observacion"].apply(normalizar_obs)
    df["carrera"]    = extraer_carrera(soup)
    df["url_fuente"] = url

    df = df.dropna(how="all").drop_duplicates(subset=["codigo"]).reset_index(drop=True)
    return df


def scrape_url(driver, url: str) -> pd.DataFrame:
    print(f"  Abriendo: {url}")
    html = obtener_html_completo(driver, url)
    df   = parse_tabla(html, url)
    print(f"  → {len(df)} registros extraídos.")
    return df


def guardar_csv(df: pd.DataFrame, ruta: Path):
    df.to_csv(ruta, index=False, encoding="utf-8-sig")
    print(f"\n✅ CSV guardado: {ruta.resolve()}")
    print(f"   {len(df)} filas  ×  {len(df.columns)} columnas")
    print("\n── Observaciones ──")
    print(df["observacion"].value_counts().to_string())
    if df["puntaje"].notna().any():
        print("\n── Estadísticas de puntaje ──")
        print(df["puntaje"].describe().round(3).to_string())


# ══════════════════════════════════════════════
# ▶ EJECUCIÓN
# ══════════════════════════════════════════════

driver = crear_driver()

try:
    if BATCH_RUTAS:
        dfs = []
        for ruta in BATCH_RUTAS:
            url = f"{BASE_URL}/{ruta.strip('/')}/results.html"
            df  = scrape_url(driver, url)
            if not df.empty:
                dfs.append(df)
            time.sleep(1.5)
        resultado = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    else:
        resultado = scrape_url(driver, URL)
finally:
    driver.quit()
    print("[INFO] Navegador cerrado.")

if not resultado.empty:
    guardar_csv(resultado, Path(ARCHIVO_SALIDA))
    display(resultado.head(15))
else:
    print("❌ No se obtuvieron datos.")

  Abriendo: https://admision.unmsm.edu.pe/Website20262/A/202/results.html
  [✓] Paginación: forzado via DataTables JS API.
  → 411 registros extraídos.
[INFO] Navegador cerrado.

✅ CSV guardado: C:\Users\confe\OneDrive\Documentos\ANÁLISIS DE DATOS UNMSM 2026\resultados_unmsm_software.csv
   411 filas  ×  8 columnas

── Observaciones ──
observacion
SIN OBSERVACIÓN          352
ALCANZÓ VACANTE           49
AUSENTE                    5
INHABILITADO (Art. 5)      5

── Estadísticas de puntaje ──
count     406.000
mean      903.069
std       227.601
min       313.875
25%       739.281
50%       878.000
75%      1059.469
max      1502.125

,codigo,apellidos_nombres,escuela,puntaje,merito_ep,observacion,carrera,url_fuente
0,374216,"Abad Maldonado, Merly Edith",INGENIERÍA DE SOFTWARE,667.250,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
1,363985,"Acosta Llacua, Clever",INGENIERÍA DE SOFTWARE,743.875,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
2,385593,"Adan Sandoval, John Jairo",INGENIERÍA DE SOFTWARE,962.000,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
3,344661,"Aguilar Noa, Guillermo André",INGENIERÍA DE SOFTWARE,720.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
4,357970,"Aguilar Palomino, Gabriel Angel Ygnacio",INGENIERÍA DE SOFTWARE,612.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
5,353008,"Ahumada Maldonado, Michael Anderson",INGENIERÍA DE SOFTWARE,740.875,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
6,394153,"Alcántara Reyes, Kimberly Camila",INGENIERÍA DE SOFTWARE,NaN,NaN,AUSENTE,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
7,341366,"Aldave Yarleque, Fabrizio",INGENIERÍA DE SOFTWARE,703.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
8,346527,"Aldazabal Quijada, Jean Paul",INGENIERÍA DE SOFTWARE,1130.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
9,360584,"Alegria Rojas, Jaren Jairo",INGENIERÍA DE SOFTWARE,1000.750,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
10,312734,"Alejandro Nalvarte, Mathias Lionel",INGENIERÍA DE SOFTWARE,725.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
11,364677,"Alfaro Huanaco, Jonathan Adrian Miguel",INGENIERÍA DE SOFTWARE,979.125,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
12,345859,"Almeyda Gonzales, Marcelo Alonso",INGENIERÍA DE SOFTWARE,1050.500,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
13,385825,"Alor Saldaña, Maicol Albino",INGENIERÍA DE SOFTWARE,868.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...
14,387248,"Altamirano Burga, Cesar Alejandro",INGENIERÍA DE SOFTWARE,981.375,NaN,SIN OBSERVACIÓN,INGENIERÍA DE SOFTWARE,https://admision.unmsm.edu.pe/Website20262/A/2...

In [22]:
import pandas as pd

df = pd.read_csv("resultados_unmsm_software.csv")

vacantes = df[df["observacion"] == "ALCANZÓ VACANTE"]

max_p = vacantes["puntaje"].max()
min_p = vacantes["puntaje"].min()

print(f"Carrera: {df['carrera'].iloc[0]}")
print(f"Vacantes obtenidas: {len(vacantes)}")
print(f"Puntaje máximo: {max_p}")
print(f"Puntaje mínimo: {min_p}")

display(vacantes[["codigo","apellidos_nombres","puntaje","merito_ep"]]
        .sort_values("puntaje", ascending=False)
        .reset_index(drop=True))

Carrera: INGENIERÍA DE SOFTWARE
Vacantes obtenidas: 49
Puntaje máximo: 1502.125
Puntaje mínimo: 1177.75

    codigo                     apellidos_nombres   puntaje  merito_ep
0   382350          Teves Chamorro, Andre Samuel  1502.125        1.0
1   356163    Falconi Tabata, Elder Andhre Kazuo  1498.125        2.0
2   377483     Espinoza Bautista, Bertolt Andrey  1495.250        3.0
3   378282            Cespedes Reyes, Andre Raul  1471.875        4.0
4   314052              Rivera Vega, Helton Jhon  1466.125        5.0
5   361748              Koo Saenz, Alexandra Mia  1463.750        6.0
6   322011          Loayza Pajuelo, Yazmin Yessú  1449.000        7.0
7   357098    Bueno Luyo, Aaron Americo Fernando  1438.750        8.0
8   323520  Huertas Balcázar, Jaquelin Alexandra  1418.750        9.0
9   330664         Arias Mendoza, Jesu Alejandro  1417.625       10.0
10  316816   Linares Sanchez, Fabrizio Alexander  1409.625       11.0
11  335074     Ramirez Carbajal, Jairo Jeanpiero  1405.625       12.0
12  327213     Villanueva Vidarte, Rodrigo Jesús  1397.625       13.0
13  325744     Morales Centurion, Gianpaul Yesid  1396.500       14.0
14  338226     Guerrero Mautino, Fernando Alonso  1381.625       15.0
15  354583      Mendoza Roncal, Esmeralda Sophia  1368.375       16.0
16  354591               Nuñez Santos, Noel Abel  1350.250       17.0
17  381326       Leon Cruzado, Gean Franco Farid  1341.125       18.0
18  342929    Hernandez Francia, Maykee Fernando  1341.125       19.0
19  394575       Coello Rodriguez, Marvin Alexis  1333.125       20.0
20  386643   Peralta Santivañez, Maryory Stefany  1333.125       21.0
21  351869        Presentación López, Luis Farid  1326.250       22.0
22  369679             Lazaro Feria, Stiven Erik  1318.750       23.0
23  387991            Farfan Rojas, Enzo Facundo  1318.250       24.0
24  357141            Meza Choquecahua, Nick Joe  1316.000       25.0
25  352251                  Tineo Tello, Gabriel  1308.000       26.0
26  333569            Vera Acosta, Gabriel Aarón  1304.000       27.0
27  340932           Pari Mamani, Lenin Reynaldo  1293.125       28.0
28  329684     Reyes Rodriguez, Daniel Alejandro  1273.750       29.0
29  360626             Lujan Godoy, Soyli Ariana  1269.750       30.0
30  374655          Ramos Sanchez, Cirilo Brayan  1259.875       31.0
31  399700        Ramirez Reyno, Felipe Santiago  1253.750       32.0
32  387665       Casiano Pariona, Jonathan Rider  1244.625       33.0
33  345676        Vilca Tarazona, Mathias Jeremy  1244.625       34.0
34  355307  Hurtado Zavala, Anthony Adrian Karim  1242.875       35.0
35  343883            Quispe Ortiz, Bruno Alonso  1232.625       36.0
36  349664          Tunqui Huaman, Piero Anghelo  1228.625       37.0
37  359208    Zegarra Ramirez, Jean Paul Esteban  1223.500       38.0
38  331185     Jaramillo Rodriguez, Kiara Dalina  1215.500       39.0
39  378435          Huaringa Flores, Jose Miguel  1215.250       40.0
40  390619           Centeno Vega, Andrew Jeremy  1214.375       41.0
41  335946       Vasquez Ojeda, Estephano Miguel  1203.500       42.0
42  340257          Moran Vilca, Samir Alexander  1195.500       43.0
43  315353       Moreno Marquina, Daudeth Arturo  1194.375       44.0
44  366059           Garro Cerdán, Héctor Daniel  1190.375       45.0
45  384631         Del Mar Huarcaya, Renzo Paolo  1189.250       46.0
46  370637        Copari Condori, Julia Milagros  1185.250       47.0
47  354280           Morales Condor, Daniel Omar  1181.250       48.0
48  334493           Tueros Garcia, Hernan David  1177.750       49.0